using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Commands.Common.Mappings
{
    public static class AuditKeyMappings
    {
        public static Dictionary<string, string> SystemSettingAuditLogDictionary { get; set; } = new Dictionary<string, string>()
        {
             { "PROCESS_EVIDENCE_SIGNING_SERVER_PROFILE", "PROCESS_EVIDENCE_CONNECTORS" },
             { "PROCESS_EVIDENCE_IS_ENABLED", "PROCESS_EVIDENCE_ENABLE" },
             { "DATA_SECURITY", "CONFIGURATIONS_DATA_SECURITY_DESCRIPTION" },
             { "DEK", "CONFIGURATIONS_ENCRYPTION_CONNECTOR" },
             { "DATA_SECURITY_DEFAULT_CONNECTOR", "CONFIGURATIONS_ENCRYPTION_CONNECTOR" },
             { "DATA_DIRECTORY", "CONFIGURATIONS_DATA_DIRECTORY_PATH" },
             { "BILLING_MARGIN_DAYS", "CONFIGURATIONS_BILLING_MARGIN_DAYS" },
             { "COMPANY_BILLING_SUPPORT_EMAIL", "CONTACT_US_EMAIL_TO" },
             { "COMPANY_BILLING_SALES_EMAIL", "CONFIGURATIONS_BILLING_SALES_EMAIL" },
             { "CONFIGURATIONS_SIGNALR_APP_NAME", "CONFIGURATIONS_REDIS_APP_NAME" },
             { "DEFAULT_SYSTEM_LOGO", "CONFIGURATIONS_BRANDING_PRODUCTLOGO_TITLE" },
             { "COMPANY_FAVICON_ICON", "CONFIGURATIONS_BRANDING_PRODUCT_FAVICON_ICON" },
             { "REPORT_DOMAIN_NAME", "REPORTS_ACCOUNT_SEARCH_DOMAINS" },
             { "BILLING_ENABLED", "CONFIGURATIONS_BILLING_ENABLE" },
             { "CONFIGURATIONS_SIGNALR_EXTERNAL_SERVICE_CONNECTION_STRING", "CONFIGURATIONS_REDIS_EXTERNAL_SERVICE_CONNECTION_STRING" },
             { "DOCUMENT_LOCK_SIGNING_SERVER_PROFILE", "DOCUMENT_LOCK_SIGNING_SERVER_CONNECTOR" },
             { "LOA_ELECTRONIC_SIGNATURE", "LEVEL_OF_ASSURANCE_SIMPLE_ELECTRONIC_SIGNATURE" },
             { "LOA_ELECTRONIC_SEAL", "LEVEL_OF_ASSURANCE_ELECTRONIC_SEAL" },
             { "LOA_ADVANCED_ELECTRONIC_SEAL", "LEVEL_OF_ASSURANCE_ADVANCD_ELECTRONIC_SEAL" },
             { "LOA_QUALIFIED_ELECTRONIC_SEAL", "LEVEL_OF_ASSURANCE_QUALIFIED_ELECTRONIC_SEAL" },
             { "LOA_ADVANCED_ELECTRONIC_SIGNATURE", "LEVEL_OF_ASSURANCE_ADVANCD_ELECTRONIC_SIGNATURE" },
             { "LOA_HIGH_TRUST_ADVANCED", "LEVEL_OF_ASSURANCE_HIGH_TRUST_ADVANCED" },
             { "LOA_QUALIFIED_ELECTRONIC_SIGNATURE", "LEVEL_OF_ASSURANCE_QUALIFIED_ELECTRONIC_SIGNATURE" }
        };
    }
}
