using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Commands.Common.Enumerations;
/* format for keys
     *
     * FUNCTIONALITY_ERRORMODULE_ERROR_IDENTIFIER_WITH_UNDERSCORES
     *
     * if functionality is not big we dont need to mention module.
     */

public enum ErrorMessages
{
    API_ERROR_AUTHORIZATION_NOT_REQUIRED,
    API_ERROR_FAILED_TO_GET_HASH,
    SERVICE_PLAN_SETTINGS_QUEUE_EXPIRY_TIME,
    COMMON_ERROR_INVALID_INPUT_VALUE,
    ATLEAST_ONE_SIGNATURE_LINE_CONTAIN_INVALID_EMAIL_ADDRESS,
    //Common error keys are used in more then one places

    #region COMMON ERROR

    CONNECTOR_OIDC_ERROR_DISOCVERY_DOCUMENT_URL_INVALID,
    COMMON_ERROR_AUTHENTICATION_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    COMMON_ERROR_TERMS_AND_SERVICES_DOES_NOT_EXIST,
    COMMON_ERROR_GENERIC,
    CSC_ERROR_BULK_SIGNING_INVALID_COUNT,
    SERVICE_PLAN_ERROR_SIMPLE_ELECTRONIC_SIGNATURES_NOT_ALLLOWED_WITH_PAY_AS_YOU_GO,
    COMMON_ERROR_LINK_INVALID_EXPIRE,
    COMMON_ERROR_PASSWORD_POLICY_INCORRECT,
    PASSWORD_POLICY_ERROR_SAMEAS_OLDPASSWORD,
    PASSWORD_POLICY_ERROR_SAMEAS_EMAIL,
    PASSWORD_POLICY_ERROR_SAMEAS_USERNAME,
    COMMON_ERROR_USER_ALREADY_EXISTS,
    COMMON_ERROR_USER_DOES_NOT_EXIST,
    API_COMMON_ERROR_RESOURCE_NOT_AVAILABLE,
    SSL_ERROR_USER_DOES_NOT_EXIST,
    API_ERROR_ENTERPRISE_ROLE_NAME_DOES_NOT_EXIST,
    COMMON_ERROR_CERTIFICATE_REVOCATION_FAILED,
    COMMON_ERROR_EMAIL_SENDING_FAILED,
    COMMON_ERROR_POST_PROCESS_COMPLETED_EMAIL_SENDING_FAILED,
    ERROR_INVALID_PFX_FILE_OR_PASSWORD,
    COMMON_ERROR_ADMINISTRATOR_ALREADY_EXISTS,
    ERROR_BUILD_VERSION_FILE_NOT_FOUND,
    COMMON_ERROR_INTERNAL_SERVER,
    COMMON_ERROR_BULK_DOCUMENT_SHARE_FAILED,
    COMMON_ERROR_BULK_DOCUMENT_RECALL_FAILED,
    ERROR_BULK_DOWNLOAD_LIMIT_REACHED,
    COMMON_DOCUMENT_DELETED,
    ERROR_DOCUMENT_CONTAINS_CORRUPT_SIGNATURES,
    ERROR_UNAUTHORIZED_ACTION,
    ERROR_SSL_CERTIFICATE_INVALID,
    ERROR_SSL_CERTIFICATE_UNAUTHORIZED,
    ERROR_SSL_CERTIFICATE_PASSWORD_INVALID,
    ERROR_SSL_CERTIFICATE_PASSWORD_REQUIRED,
    ERROR_REMOVE_ADMINISTRATOR_USER,
    COMMON_ERROR_INVALID_URL,
    ERROR_INVALID_JSON_FILE,
    COMMON_SETTINGS_ENTERPRISE_EXPORT_ERROR,
    COMMON_SETTINGS_ENTERPRISE_IMPORT_ERROR,
    COMMON_ERROR_INVALID_FILE_FORMAT,
    COMMON_ERROR_INVALID_EMAIL,
    COMMON_ERROR_INCONVENIENCE,
    COMMON_ERROR_FROM_DATE_IS_GREATER_THAN_TO_DATE,
    COMMON_ERROR_INVALID_REQUIRED_INPUT_PARAMETERS,
    /// <summary>
    /// Error in case of controller path not found(used in IOCControllerFactory(WEB and Admin))
    /// </summary>
    ERROR_CONTROLLER_PATH_NOT_FOUND,

    #endregion COMMON ERROR

    #region REGISTER ERROR

    REGISTER_ERROR_LICENSE_COUNT_REACHED,
    REGISTER_ERROR_USER_DEFAULT_DOCUMENT_FAILED,
    REGISTER_ERROR_PLAN_USER_LIMIT_REACHED,
    REGISTER_ERROR_LICENSE_ENTERPRISE_COUNT_REACHED,
    REGISTER_ERROR_ENTERPRISE_ADMIN_CREDENTIALS_REQUIRED,
    REGISTER_ERROR_AGREE_TERMS_SERVICES,
    ERROR_COUNTRY_NOT_SUPPORTED,
    ERROR_TIMEZONE_NOT_SUPPORTED,
    ERROR_INVALID_CLIENT,
    ERROR_CHANGE_TIMEZONE_NOT_ALLOWED,
    ERROR_CHANGE_COUNTRY_NOT_ALLOWED,
    ERROR_INVALID_REFRESH_TOKEN,
    ERROR_LANGUAGE_NOT_SUPPORTED,
    REGISTER_ERROR_ENTERPRISE_ALREADY_EXISTS,
    ERROR_SSL_USER_MAPPING,
    API_REGISTER_ERROR_USER_CREDENTIALS_REQUIRED,
    USER_ERROR_USER_IS_NOT_REGISTERED_IN_THE_SYSTEM,
    ERROR_USER_ALREADY_A_GATEKEEPER_OF_ANOTHER_USER,

    #endregion REGISTER ERROR

    #region INVITED USER ERROR

    INVITEDUSER_ACCEPT_FAILED,
    INVITEDUSER_REJECT_FAILED,
    INVITEUSER_USER_ALREADY_INVITED,
    INVITEDUSER_ERROR_USER_IS_ENTERPRISE_OWNER,
    INVITEDUSER_ERROR_USER_IS_PART_OF_ENTERPRISE,
    INVITATION_ERROR_OWNER_CANNOT_JOIN_ANOTHER_ENTERPRISE,
    INVITEDUSER_ERROR_REGISTRATION_DISABLED,

    #endregion INVITED USER ERROR

    #region DELEGATION ERROR

    DELEGATION_ADD_FAILED,
    DELEGATION_REMOVE_FAILED,
    DELEGATE_ERROR_CANNOT_SET_URSELF_AS_DELEGATOR,
    DELEGATE_ERROR_MAXIMUM_LIMIT_REACHED,
    DELEGATE_ERROR_SAME_TIME_ALREADY_ASSIGNED,
    DELEGATE_ERROR_NO_DELEGATE_SELECTED,

    #endregion DELEGATION ERROR

    #region LOGIN ERROR

    LOGIN_ERROR_USER_LOCKED,
    LOGIN_ERROR_USER_NOT_ACTIVATED,
    LOGIN_ERROR_SH_NOT_FOUND,
    LOGIN_ERROR_CREATE_SH_ID,
    LOGIN_ERROR_USERNAME_PASSWORD_INCORRECT,
    LOGIN_ERROR_ACCESSLEVEL,
    RE_AUTHENTICATION_IS_REQUIRED,
    LOGIN_ERROR_GUEST_USER_NOT_REGISTERED,
    LOGIN_ERROR_PUBLIC_AUTHENTICATION_NOT_ALLOWED,
    LOGIN_ERROR_EMAIL_NOT_AVAILABLE,
    LOGIN_ERROR_TWO_FACTOR_AUTHENTICATION_REQUIRED,
    LOGIN_ERROR_AGREE_TERM_AND_SERVICES,
    LOGIN_ERROR_EMAIL_NOT_AVAILABLE_IN_ENTERPRISE,
    LOGIN_AUTHENTICATION_ERROR_IDENTITY_PROVIDER_NOT_DEFINED,
    LOGIN_AUTHENTICATION_SIGNINGHUB_ID_NOT_AVAILABLE,
    LOGIN_ERROR_EMAIL_PASSWORD_INCORRECT,
    LOGIN_ERROR_PASSWORD_INCORRECT,
    LOGIN_ERROR_LOGIN_PROFILE_NOT_AVAILABLE,
    LOGIN_ERROR_AUTO_TRIGGER_AUTH_PROFILE_VALIDATION,
    LOGIN_ERROR_PASSWORD_RESET_BY_ADMIN,

    #endregion LOGIN ERROR

    #region FORGOT PASSWORD ERROR

    FORGOTPASSWORD_ERROR_EMAIL_NOT_FOUND,

    //   FORGOTPASSWORD_ERROR_EMAIL_NOT_ACTIVATED,
    FORGOTPASSWORD_ERROR_SECURITY_ANSWER_INCORRECT,

    FORGOTPASSWORD_ERROR_RESET_PASSWORD_FAILED,

    // FORGOTPASSWORD_ERROR_SH_NOT_EXIST,
    FORGOTPASSWORD_ERROR_INVALID_OLD_PASSWORD,

    FORGOTPASSWORD_ERROR_CONFIRM_PASSWORD,

    #endregion FORGOT PASSWORD ERROR

    #region ACTIVATE USER ERROR

    ACTIVATEUSER_ACTIVATIONCODE_INVALID,
    ACTIVATEUSER_ERROR_USER_ALREADY_ACTIVATED,
    ERROR_ACTIVATED_USER_DELETED,
    ERROR_ACTIVATED_USER_IS_GUEST,

    #endregion ACTIVATE USER ERROR

    #region DOCUMENT LIST ERROR

    DOCUMENT_LIST_FAILED,

    #endregion DOCUMENT LIST ERROR

    #region DOCUMENT ERROR

    DOCUMENT_ERROR_DOCUMENT_DOES_NOT_EXIST,
    DOCUMENT_ERROR_PACKAGE_DOES_NOT_EXIST,
    DOCUMENT_ERROR_LICENSE_COUNT_REACHED,
    DOCUMENT_ERROR_SERVICEPLAN_COUNT_REACHED,
    DOCUMENT_ERROR_SERVICEPLAN_MAX_SIZE_EXCEEDED,
    DOCUMENT_ERROR_SERVICEPLAN_STORAGE_LIMIT_EXCEEDED,
    DOCUMENT_ERROR_TYPE_CONVERSION_FAILED,
    DOCUMENT_ERROR_PDF_VALIDATION_FAILED,
    DOCUMENT_ERROR_DOCUMENT_UPLOAD_FAILED,
    DOCUMENT_ERROR_DOCUMENT_REMOVE_FAILED,
    DOCUMENT_ERROR_NOT_AN_ISO_STANDARD_ACROFORM_PDF,
    DOCUMENT_ERROR_ACCESS_DURATION_EXPIRES,
    DOCUMENT_ERROR_ACCESS_DURATION_TIME_NOT_STARTED,
    DOCUMENT_CERTIFY_WITH_NO_CHANGES_ALLOWED,
    DOCUMENT_ERROR_ADD_REVISION,
    DOCUMENT_CHANGE_OWNER_ERROR_NOT_BELONG_TO_USER,
    DOCUMENT_CHANGE_OWNER_ERROR_USER_INACTIVE,
    DOCUMENT_CHANGE_OWNER_ERROR_INVALID_PACKAGE_STATUS,
    ERROR_DOCUMENT_HAS_ALREADY_SIGNATURE_FIELD,
    DOCUMENT_ERROR_NON_DRAFT_MODE,
    DOCUMENT_ERROR_PENDING_MODE,
    ERROR_COLLABORATOR_PERMISSION_NOT_ALLOWED,
    ERROR_DOCUMENT_LAST_DOCUMENT_REACHED,
    ERROR_DOCUMENT_UNABLE_TO_ADD_TEXT_FIELD,
    ERROR_DOCUMENT_HAS_DIFFERENT_DIMENSIONS,
    DOCUMENT_DOWNLOAD_ERROR_PERMISSION,
    DOCUMENT_DOWNLOAD_ERROR_OTP_PASSWORD,
    DOCUMENT_DOWNLOAD_ERROR_PASSWORD_PERMISSION,
    DOCUMENT_DOWNLOAD_ERROR_DELEGATION_TIME_NOT_STARTED,
    DOCUMENT_DOWNLOAD_ERROR_DELEGATION_TIME_EXPIRES,
    DOCUMENT_ERROR_PACKAGE_ID_IS_NOT_UNIQUE,
    DOCUMENT_ERROR_SORT_ORDER_IS_NOT_UNIQUE,
    DOCUMENT_ERROR_DOCUMENTS_COUNT_IS_LESS_THAN_DOCUMENTS_IN_PACKAGE,
    DOCUMENT_ERROR_DOCUMENTS_COUNT_IS_GREATER_THAN_DOCUMENTS_IN_PACKAGE,
    DOCUMENT_ERROR_REORDER_LIST_DOES_NOT_CONTAIN_ALL_DOCUMENTS_OF_PACKAGE,
    DOCUMENT_ERROR_REORDER_ASSIGNED_ORDER_IS_GREATER_THAN_DOCUMENTS_COUNT,
    COLLABORATOR_ERROR_REORDER_ASSIGNED_ORDER_IS_GREATER_THAN_COLLABORATOR_COUNT,
    BULK_SIGN_ERROR_ACCESS_DURATION_TIME_NOT_STARTED,
    BULK_SIGN_ERROR_DELEGATION_TIME_EXPIRED,
    BULK_SIGN_ERROR_OTP_PASSWORD,
    DOCUMENT_PRINT_ERROR_ACCESS_DURATION_TIME_NOT_STARTED,
    DOCUMENT_PRINT_ERROR_DELEGATION_TIME_EXPIRES,
    VIEWER_ERROR_FORM_FIELDS_FILL,
    SIGN_PANEL_ERROR_FILL_INPERSON,
    VIEWER_SEQUENTIAL_SIGN_ERROR,
    BULK_SIGN_ESIGN_OTP,
    BULK_SIGN_SIGNER_MSG,
    DOCUMENT_ERROR_ACCESS_PASSWORD_INVALID,
    DOCUMENT_ERROR_PACKAGE_EMPTY,
    ERROR_FORM_FIELDS_READ_ONLY_FIELD_CAN_NOT_BE_FILLED,
    BULK_SIGN_INVALID_STATE_MESSAGE,
    BULK_SIGN_ERROR_ATTACHMENTS_REQUIRED,
    ATTACHMENTS_ERROR_NOT_ADDED,
    DOCUMENT_ERROR_INVALID_EXTENSION,
    DOCUMENT_ERROR_INVALID_NAME,
    DOCUMENT_PRINT_ERROR_PERMISSION,
    ATTACHMENT_ERROR_NOT_ALLOWED_IN_SIGNED_DOCUMENTS,
    DOCUMENT_ERROR_UNABLE_TO_PARSE_ATTACHMENTS,
    DOCUMENT_ERROR_APPEND_MODE_ITEXTSHARP,
    DOCUMENT_PRINT_ERROR_OTP_PASSWORD,
    DOCUMENT_PRINT_ERROR_PASSWORD_PERMISSION,
    FIELD_ERROR_CAN_NOT_ADD_MULTIPLE_QR_CODES,
    FIELD_ERROR_CAN_NOT_ADD_MULTIPLE_UINIQUE_IDENTIFIERS,

    OTP_METHOD_INVALID,

    #endregion DOCUMENT ERROR

    #region CONTACTS ERROR

    CONTACT_ADD_FAILED,
    CONTACT_NO_CONTACT_IN_CSV_OR_FILE_CORRUPT,
    CONTACT_ERROR_PARSING_CSV_FILE,
    SETTINGS_CONTACT_ERROR_ALREADY_EXIST,
    ERROR_SETTINGS_CONTACT_INVALID_CSV_FILE,

    #endregion CONTACTS ERROR

    #region GROUP ERROR

    GROUP_ALREADY_EXIST,
    GROUP_ADD_FAILED,
    GROUP_CONTACT_ALREADY_EXIST_IN_GROUP,
    GROUP_ERROR_MEMEBER_ALREADY_EXISTS,
    SETTINGS_GROUP_ERROR_CHOOSE_GROUP,

    #endregion GROUP ERROR

    #region WORKFLOW ERROR

    WORKFLOW_ADD_COLLABORATOR_FAILED,
    WORKFLOW_UPDATE_COLLABORATOR_FAILED,
    WORKFLOW_ERROR_UPDATE_COLLABORATOR_TASK_FAILED,
    WORKFLOW_REMOVE_COLLABORATOR_FAILED,
    WORKFLOW_ADD_INITIALS_FAILED,
    WORKFLOW_REMOVE_INITIALS_FAILED,
    WORKFLOW_ADD_INPERSON_FAILED,
    WORKFLOW_REMOVE_INPERSON_FAILED,
    WORKFLOW_SIGN_FIELD_FAILED,
    WORKFLOW_FILL_INITIAL_FAILED,
    WORKFLOW_SIGN_INPERSON_FAILED,
    WORKFLOW_SET_TYPE_FAILED,
    WORKFLOW_ADD_REVIWER_FAILED,
    WORKFLOW_SAVE_PERMISSIONS_FAILED,
    WORKFLOW_SAVE_OFFPAGE_COMMENT_FAILED,
    WORKFLOW_SAVE_FORM_FIELDS_FAILED,
    WORKFLOW_ERROR_DECLINED_FAILED,
    WORKFLOW_RECALLED_FAILED,
    CERTIFY_SIGNATURE_WILL_BE_CORRUPT_BECAUSE_OF_INITIAL_OR_INPERSON,
    WORKFLOW_ERROR_VALIDATION_FAILED,
    WORKFLOW_PROCESS_EMAIL_SENDING_FAILED,
    DOCUMENT_ERROR_NOT_BELONG_TO_USER,
    DOCUMENT_ERROR_NOT_BELONG_TO_ENTERPRISE,
    DOCUMENT_ERROR_CANNOT_DOWNLOAD_IN_DRAFT,
    WORKFLOW_ERROR_FIELD_UNASSIGNED,
    WORKFLOW_ERROR_FIELD_PLACEHOLDER,
    WORKFLOW_ERROR_CHANGE_PLACEHOLDER,
    WORKFLOW_ERROR_COLLABORATOR_SIGNATURE_FIELD_NOT_ADDED,

    //WORKFLOW_ERROR_CERTIFY_SIGNATURE_CORRUPT_NO_ANNOTATION,//not used any more
    //WORKFLOW_ERROR_CERTIFY_SIGNATURE_CORRUPT_NO_CHANGES,//Not used any more
    WORKFLOW_ERROR_SIGNATURE_FIELD_UNASSIGNED,

    WORKFLOW_ERROR_USER_ALREADY_SET_AS_GATEKEEPER_OF_OTHER_USER,

    WORKFLOW_ERROR_SERVICEPLAN_WORKFLOW_LIMIT_REACHED,
    WORKFLOW_ERROR_COLLABORATOR_NOT_VALID,

    //WORKFLOW_PROCESS_TO_NEXT_COLLABORATOR_FAILED, //not used (replaced with common error generic)
    WORKFLOW_PROCESS_AFTER_SIGNING_FAILED,

    WORKFLOW_ERROR_DELEGATION_RIGHTS_ALTERED,
    WORKFLOW_ERROR_MULTIPLE_DIGITAL_SIGNATURE_NOT_ALLOWED,
    WORKFLOW_ERROR_INPERSON_FAILED_WITH_DIGITAL_SIGNATURE_NOT_ALLOWED,
    WORKFLOW_ERROR_ADD_TEXT_ADD_ATTACHMENT_INITIAL_NOT_ALLOWED,
    WORKFLOW_ERROR_DELETE_ATTACHMENT_NOT_ALLOWED,
    WORKFLOW_ERROR_INPERSON_OR_INITIAL_AFTER_DIGITAL_SIGNATURE_NOT_ALLOWED,
    WORKFLOW_ERROR_COLLABORATOR_DOES_NOT_EXIST,
    WORKFLOW_MID_FLOW_CHANGE_COLLABORATOR_FAILED,
    WORKFLOW_ERROR_UNABLE_TO_ADD_FORM_FIELD,
    WORKFLOW_ERROR_UNABLE_TO_UPDATE_FORM_FIELD,
    WORKFLOW_ERROR_UNABLE_TO_REMOVE_FORM_FIELD,
    WORKFLOW_ERROR_READ_ONLY_WORKFLOW,
    FIELD_ERROR_QR_CODE_NOT_ALLOWED_FOR_INDIVIDUAL_WORKFLOW,
    WORKFLOW_ERROR_CHANGE_SIGNER_PERMISSION,
    WORKFLOW_ERROR_UNABLE_TO_FILL_FORM_FIELD,
    WORKFLOW_ERROR_INDIVIDUAL_COLLABORATOR_NOT_SAME_TYPE,
    WORKFLOW_RECALLED_FAILED_DOCUMENT_IS_NOT_OWNER,
    WORKFLOW_ERROR_ADD_TEXT_NOT_ALLOWED_NO_CHANGES,
    WORKFLOW_ERROR_ADD_TEXT_NOT_ALLOWED_NO_FORM_FILLING,
    START_NEW_WORKFLOW_FAILED,
    WORK_FLOW_VALIDATEDELEGATOR_FAILED,
    WORK_FLOW_FINISH_ERROR,
    ERROR_WORKFLOW_TYPE_DOES_NOT_ALLOW_TO_UPDATE_PERMISSION,
    ERROR_DRAFT_SIGNER_TASK_PROCESSED,
    WORKFLOW_ERROR_FIELD_SAME_NAME,
    WORKFLOW_ERROR_SHARING_ORDER_LESS_THAN_ONE,
    WORKFLOW_ERROR_SHARING_ORDER_LIMIT_EXCEEDS,
    BULK_SIGN_AND_SHARE_WORKFLOW_NEXT_COLLABORATOR_NOT_AVAILABLE,
    BULK_SIGN_AND_SHARE_ERROR_WORKFLOW_TYPE_INDIVIDUAL_CANT_PROCEED,
    WORKFLOW_ERROR_COLLABORATOR_REMINDER_DURATION_SHOULD_BE_GREATER_THAN_ZERO,
    WORKFLOW_ERROR_FIELD_ALREADY_PROCESSED,
    WORKFLOW_ERROR_FIELD_DOES_NOT_EXIST,
    FIELD_ERROR_UNIQUE_IDENTIFIER_NOT_ALLOWED,

    #endregion WORKFLOW ERROR

    #region SETTINGS USER ERROR

    SETTINGS_ERROR_USER_PROFILE_UPDATE,
    SETTINGS_USER_SECURITY_FAILED,
    SETTINGS_USER_DIGITAL_SIGNATURE_FAILED,
    SETTINGS_USER_SIGNATURE_APPEARANCE_FAILED,
    SETTINGS_USER_ADD_CONTACT_FAILED,
    SETTINGS_USER_ADD_GROUP_FAILED,
    SETTINGS_USER_ADD_TEMPLATES_FAILED,
    SETTINGS_USER_EDIT_TEMPLATES_FAILED,
    SETTINGS_USER_REMOVE_TEMPLATES_FAILED,
    SETTINGS_USER_REMOVE_LIBRARY_FAILED,
    SETTINGS_USER_ADD_LIBRARY_FAILED,
    SETTINGS_USER_UPDATE_LIBRARY_FAILED,
    SETTINGS_USER_UPDATE_STATS_FAILED,
    SETTINGS_ENTERPRISE_SIGNING_REASON_ALREADY_EXIST,
    SETTINGS_ENTERPRISE_SIGNING_REASON_DOES_NOT_EXIST,
    GET_USER_SETTINGS_FAILED,
    SETTINGS_ENTERPRISE_USER_DELETE_ERROR,
    SETTINGS_PROFILE_MOBILE_NUMBER_TOOLTIP,

    #endregion SETTINGS USER ERROR

    #region TEMPLATE ERRORS

    TEMPLATE_ERROR_CONTAINS_NO_COLLABORATOR,
    TEMPLATE_ERROR_LIMIT_REACHED,
    TEMPLATE_ERROR_TEMPLATE_COUNT_NOT_UPDATED_IN_USER_SETTINGS,
    TEMPLATE_ERROR_ALREADY_EXISTS_WITH_SAME_NAME,
    SETTINGS_ENTERPRISE_TEMPLATE_IMPORT_ERROR_ALREADY_EXIST,
    TEMPLATE_ERROR_UPDATE_WORKFLOW_FAILED,
    TEMPLATE_ERROR_CREATE_TEMPLATE_FAILED,
    TEMPLATE_ERROR_WORKFLOW_SERIALIZATION_FAILED,
    TEMPLATE_ERROR_GET_DOCUMENT_FOR_TEMPLATE_DOCUMENT,
    TEMPLATE_ERROR_GET_TEMPLATE,
    TEMPLATE_ERROR_TEMPLATE_IS_ALREADY_APPLIED,
    TEMPLATE_ERROR_WORKFLOW_DESERIALIZATION_FAILED,
    TEMPLATE_ERROR_DOCUMENT_CONTAINS_UNASSIGNED_OR_FORM_FIELDS,
    TEMPLATE_ERROR_APPLY_TEMPLATE_FAILED,
    TEMPLATE_ERROR_EDIT_TEMPLATE_FAILED,
    TEMPLATE_ERROR_APPLY_INVALID_PAGES,
    TEMPLATE_ERROR_APPLY_INVALID_PAGE_SIZE,
    TEMPLATE_ERROR_APPLY_INVALID_FORM_FIELDS,
    TEMPLATE_ONLYME_ERROR_MULTIPLE_USERS_NOT_ALLOWED,
    TEMPLATE_ONLYME_ERROR_ONLY_SIGNER_ROLE_ALLOWED,
    TEMPLATE_ONLYME_ERROR_RECIPEINT_IS_NOT_LOGGED_IN_USER,
    TEMPLATE_ONLYME_ERROR_EMPTY_RECIPEINT_NOT_ALLOWED,
    TEMPLATE_ONLYME_ERROR_GROUP_NOT_ALLOWED,
    TEMPLATE_ERROR_READ_ONLY_CHANGE_SIGNER_PERMISSION_NOT_ALLOWED,
    TEMPLATE_ERROR_APPLY_PRIVATE_TEMPLATE_NOT_ALLOWED,

    #endregion TEMPLATE ERRORS

    #region ADSS ERRORS

    CERTIFICATE_REVOCATION_FAILED,
    CERTIFICATE_GENERATION_FAILED,
    CERTIFICATE_AUTHORIZATION_FAILED,
    ADSS_ERROR_SERVER_NOT_AVAILABLE,

    #endregion ADSS ERRORS

    #region UserCertificate ERRORS

    CERTIFICATE_FAILD_TO_ADD,

    #endregion UserCertificate ERRORS

    #region QUOTA ERRORS

    DIGITAL_SIGNATURES_LIMIT_REACHED,
    DISK_SPACE_LIMIT_REACHED,
    QUOTA_LIMIT_REACHED,

    #endregion QUOTA ERRORS

    #region PROFILE_ERRORS

    PROFILE_ALREADY_EXISTS,
    ERROR_LICENSE_MODULE_DISABLED,
    ERROR_PROFILE_USING_BY_SERVICE_PLAN,
    ERROR_PROFILE_ADD_FAILED,
    ERROR_GET_PROFILE_FAILED,
    ERROR_UPDATE_PROFILE_FAILED,
    ERROR_REMOVE_PROFILE_FAILED,
    ERROR_PROFILE_DOESNOT_EXIST,
    ERROR_PROFILE_IS_INACTIVE,
    ERROR_PROFILE_NAME_EMPTY,
    ERROR_PROFILE_USING_BY_SYSTEM_SETTINGS,
    ERROR_CERTIFICATION_PROFILE_USING_IN_DOCUMENT_LOCK_ESEAL_CAPACITY,
    ERROR_SIGNING_PROFILE_USING_IN_EVIDENCE_REPORT,
    ERROR_SIGNING_PROFILE_USING_IN_DOCUMENT_LOCK,
    ERROR_PROFILE_USING_BY_ENTERPRISE_ROLES,
    ERROR_PROFILE_USING_BY_ENTERPRISE_ACTIVE_DIRECTORY_PROVISONING,
    SIGNING_PROFILE_ERROR_CONFIGURED_IN_ARCHIVING,
    CERTIFICATION_PROFILE_ERROR_CONFIGURED_IN_ARCHIVING,

    #endregion PROFILE_ERRORS

    #region ENTERPRISE_ERRORS

    ENTERPRISE_DOESNOT_EXISTS,
    ERROR_NOT_ENERPRISE_USER,
    ENTERPRISE_ERROR_NOT_BELONG_TO_USER,
    ERROR_ENTERPRISE_NOT_AUTHORIZED_TO_UPDATE_ENTERPRISE,
    ERROR_ENTERPRISE_INVALID_AUTO_TRIGGER_AUTH_PROFILE,
    ENTERPRISE_USER_ERROR_SIGNATURE_LIMIT_REACHED,
    ENTERPRISE_USER_ERROR_SIMPLE_ELECTRONIC_SIGNATURE_LIMIT_REACHED,
    ENTERPRISE_USER_ERROR_DISK_SPACE_LIMIT_REACHED,
    ENTERPRISE_USER_ERROR_DOCUMENTS_SHARE_LIMIT_REACHED,
    ENTERPRISE_USER_ERROR_UPLOAD_SIZE_LIMIT_REACHED,
    ENTERPRISE_USER_ERROR_TEMPLATES_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_SIGNATURE_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_SIMPLE_ELECTRONIC_SIGNATURE_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_DISK_SPACE_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_DOCUMENTS_SHARE_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_UPLOAD_SIZE_LIMIT_REACHED,
    ENTERPRISE_USER_SAVE_ERROR_TEMPLATES_LIMIT_REACHED,

    #endregion ENTERPRISE_ERRORS

    #region CONNECTOR_ERRORS

    ERROR_CONNECTOR_ADD_FAILED,
    ERROR_CONNECTOR_UPDATION_FAILED,
    ERROR_CONNECTOR_REMOVAL_FAILED,
    ERROR_CONNECTOR_DOESNOT_EXISTS,
    ERROR_CONNECTION_PROVIDER_DOESNOT_EXIST,
    ERROR_CONNECTION_PROVIDER_PARAMETER_DOESNOT_EXIST,
    ERROR_CONNECTOR_ALREADY_EXISTS_IN_PROFILE,
    ERROR_CONNECTOR_ALREADY_EXISTS_IN_SYSTEM_SETTINGS,
    ERROR_CONNECTOR_ALREADY_EXISTS_IN_BILLING,
    ERROR_CONNECTOR_ALREADY_EXISTS_IN_SERVICEPLAN,
    ERROR_CONNECTOR_IS_INACTIVE,
    ERROR_CONNECTOR_SSL_CERTIFICATE_OR_PASSWORD_REQUIRED,

    #endregion CONNECTOR_ERRORS

    #region LICENSE_ERRORS

    ERROR_LICENSE_FILE_INVALID,
    ERROR_LICENSE_MODULE_INVALID,
    ERROR_LICENSE_SIGNATURE_INVALID,
    LICENSE_ERROR_SIGNATURE_MODULE_IS_REQUIRED,
    ERROR_LICENSE_INACTIVE,
    ERROR_LICENSE_WORKFLOW_LIMIT_REACHED,
    ERROR_LICENSE_MODULE_INVALID_OR_SIGNATURE_LIMIT_REACHED,
    UNABLE_TO_CONNECT_TO_DATABASE,
    ERROR_LICENSE_SIGNATURE_QUOTA_LIMIT_EXCEEDS_ALLOWED_LIMIT,
    ERROR_LICENSE_SIMPLE_ELECTRONIC_SIGNATURE_QUOTA_LIMIT_EXCEEDS_ALLOWED_LIMIT,

    #endregion LICENSE_ERRORS

    #region SYSTEM_SETTINGS

    ERROR_SYSTEM_SETTINGS_FAILED_TO_UPDATE,
    ERROR_SYSTEM_SETTINGS_FAILED_TO_GET,
    ERROR_UTC_TO_TIMEZONE_CONVERSION,
    ERROR_ARCHIVE_PFX_PASSSWORD_INVALID,

    #endregion SYSTEM_SETTINGS

    #region SERVICEPLAN_ERROR

    ERROR_LICENSE_TOTAL_USER_LIMIT_EXCEEDS,
    ERROR_LICENSE_TOTAL_SIGNATURE_LIMIT_EXCEEDS,
    ERROR_LICENSE_TOTAL_SIMPLE_ELECTRONIC_SIGNATURE_LIMIT_EXCEEDS,
    ERROR_LICENSE_TOTAL_DOCUMENT_SHARE_LIMIT_EXCEEDS,
    ERROR_SERVICEPLAN_ADD_FAILED,
    ERROR_SERVICEPLAN_UPDATION_FAILED,
    ERROR_SERVICEPLAN_USING_BY_USER,
    ERROR_SERVICEPLAN_USING_BY_SYSTEM_SETTINGS,
    ERROR_SERVICEPLAN_REMOVAL_FAILED,
    ERROR_SERVICEPLAN_DOESNOT_EXIST,
    ACTIVATEUSER_PASSWORD_UPDATE_FAILED,
    ERROR_REMOVE_USER_SERVICEPLAN_FAILED,
    ERROR_SERVICE_PLAN_FEATURES_UNAVAILABLE,
    SERVICE_PLAN_ERROR_DISKSPACE_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_SIGNATURE_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_SIMPLE_ELECTRONIC_SIGNATURE_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_OWNER_SIGNATURE_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_USERS_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_TEMPLATES_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_WORKFLOWS_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_UPLOAD_SIZE_LIMIT_REACHED,
    SERVICE_PLAN_ERROR_BILLING_TYPE_IS_NOT_VALID,
    SERVICE_PLAN_ERROR_RESETING_FAILD,
    SERVICE_PLAN_ERROR_USER_CANNOT_SWITCH_TO_THIS_PLAN,
    SERVICE_PLAN_ERROR_CHANGE_SERVICE_PLAN_FAILED,
    SERVICE_PLAN_ERROR_CHANGE_SERVICE_PLAN_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_INITIALS_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_INPERSONS_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_FORMFIELDS_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_REVIEWER_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_OTP_DISABLED,
    SERVICE_PLAN_ERROR_EDITOR_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_DIGITAL_SIGNATURE_NOT_ALLOWED, // Digital signatures not allowed
    SERVICE_PLAN_ERROR_SEND_A_COPY_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_INDIVIDUAL_PLAN_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_AUTHORIZED_REMOTE_SIGNING_NOT_ALLOWED,
    LICENSE_ERROR_AUTHORIZED_REMOTE_SIGNING_NOT_ALLOWED,
    OTP_ERROR_AUTHORIZED_REMOTE_SIGNING_NOT_ALLOWED,
    SERVICEPLAN_ERROR_DOWN_GRADE,
    SERVICEPLAN_ERROR_SAME_SERVICEPLAN,
    SERVICEPLAN_ERROR_APPEARANCE_USED_IN_ENTERPRISE_ROLES,

    #endregion SERVICEPLAN_ERROR

    #region SIGNING_ERROR

    SIGNING_ERROR_SERVER_SIGNING_FAILED,
    SIGNING_ERROR_MOBILE_LOCAL_SIGNING_FAILED,
    SIGNING_ERROR_LOCAL_WORD_SIGNING,
    ERROR_VIEWER_FILL_SIGNATURE_FIELD,
    LOCAL_SIGN_ERROR_DICTIONARY_SIZE_IS_SMALL,
    ERROR_LOCAL_SIGNING_FAILED,
    SETTINGS_LEGAL_NOTICE_NAME_ALREADY_EXIST,
    SIGNING_ERROR_FAILED,
    SIGNING_ERROR_CERTIFICATE_CHAIN_NOT_COMPLETED,
    SIGNING_ERROR_CERTIFICATE_REVOKED,
    SIGNING_ERROR_CERTIFICATE_SUSPENDED,

    #endregion SIGNING_ERROR

    #region DOCUMENT_LIBRARY_ERRORS

    DOCUMENT_LIBRARY_ERROR_REMOVE_FAILED,
    DOCUMENT_LIBRARY_ERROR_UPDATE_FAILED,
    DOCUMENT_LIBRARY_ERROR_GET_FAILED,
    DOCUMENT_LIBRARY_ERROR_ADD_FAILED,

    #endregion DOCUMENT_LIBRARY_ERRORS

    #region SUB_TASK_ERROR

    SUB_TASK_ERROR_UNABLE_TO_REMOVE,

    #endregion SUB_TASK_ERROR

    #region OTP_ERROR

    OTP_ERROR_DOES_NOT_MATCH,
    ERROR_OTP_REQUIRED,
    ERROR_OTP_MOBILE_NUMBER_ALREADY_EXIST,
    OTP_ERROR_MOBILE_NUMBER_EMPTY,
    OTP_ERROR_INVALID_MOBILE_NUMBER,
    ERROR_OTP_UNABLE_TO_SEND,
    GENERIC_SMS_ERROR,

    #endregion OTP_ERROR

    #region EMAIL_ERROR

    ENTERPRISE_EMAILS_ERROR_UNABLE_TO_GET,
    USER_EMAILS_ERROR_UNABLE_TO_GET,
    USER_EMAILS_ERROR_UNABLE_TO_RESET,
    ENTERPRISE_EMAILS_ERROR_UNABLE_TO_RESET,
    ERROR_EMAIL_ATTACHMENT_SIZE_EXCEEDS,
    ERROR_EMAIL_CONTENT_INVALID_OR_EMPTY,

    #endregion EMAIL_ERROR

    #region VERIFICATION_ERROR

    VERIFICATION_ERROR_SERVICE_NOT_AVAILABLE,
    VERIFICATION_ERROR_UNABLE_TO_GET,

    #endregion VERIFICATION_ERROR

    #region AccessManagementErrors

    SHARE_DOCUMENT_NOT_ALLOWED_IN_LICENSE,
    SHARE_DOCUMENT_NOT_ALLOWED_IN_SERVICEPLAN,
    SERVER_SIGN_NOT_ALLOWED_IN_LICENSE,
    SERVER_SIGN_NOT_ALLOWED_IN_SERVICEPLAN,
    LOCAL_SIGN_NOT_ALLOWED_IN_LICENSE,
    LOCAL_SIGN_NOT_ALLOWED_IN_SERVICEPLAN,
    OTP_NOT_ALLOWED_IN_LICENSE,
    OTP_NOT_ALLOWED_IN_SERVICEPLAN,
    OTP_EMAIL_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_DRAW_FOR_WEB_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_DRAW_FOR_MOBILE_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_TEXT_FOR_WEB_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_TEXT_FOR_MOBILE_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_UPLOAD_FOR_WEB_NOT_ALLOWED_IN_SERVICEPLAN,
    HAND_SIGNATURE_UPLOAD_FOR_MOBILE_NOT_ALLOWED_IN_SERVICEPLAN,
    PASSWORD_AUTHENTICATION_NOT_ALLOWED_IN_SERVICEPLAN,
    PASSWORD_AUTHENTICATION_NOT_ALLOWED_IN_LICENSE,
    SSL_AUTHENTICATION_NOT_ALLOWED_IN_SERVICEPLAN,
    SSL_AUTHENTICATION_NOT_ALLOWED_IN_LICENSE,
    INTEGRATION_NOT_ALLOWED_IN_LICENSE,
    INTEGRATION_NOT_ALLOWED_IN_SERVICEPLAN,
    BILLING_NOT_ALLOWED_IN_LICENSE,
    BILLING_NOT_ALLOWED_IN_SYSTEM_SETTINGS,
    BILLING_NOT_ALLOWED_IN_SERVICE_PLAN,
    VAT_SUBMISSION_NOT_ALLOWED_IN_SYSTEM_SETTINGS,
    VAT_ERROR_VALIDATION_FAILED,
    TIMEZONE_CHANGE_NOT_ALLOWED_IN_SYSTEM_SETTINGS,
    ERROR_CHANGE_LANGUAGE_NOT_ALLOWED,
    FORM_FIELDS_NOT_ALLOWED_IN_SERVICEPLAN,
    SHAREPOINT_NOT_ALLOWED_IN_LICENSE,
    SHAREPOINT_NOT_ALLOWED_IN_SERVICEPLAN,
    REVIEWER_NOT_ALLOWED_IN_SERVICEPLAN,
    INITIALS_NOT_ALLOWED_IN_SERVICEPLAN,
    INPERSONS_NOT_ALLOWED_IN_SERVICEPLAN,
    SERVICE_PLAN_ERROR_ATTACHMENTS_AND_MERGING_NOT_ALLOWED,
    SERVICE_PLAN_ERROR_CLOUD_DRIVES_NOT_ALLOWED,
    PUBLISH_DOCUMENT_HISTORY_NOT_ALLOWED_IN_SERVICEPLAN,
    RERVIEWER_CANNOT_HAVE_SIGNATURE_FIELD,
    REVIEWER_CANNOT_HAVE_INPERSON_FIELD,
    EDITIOR_CANNOT_HAVE_SIGNATURE_FIELD,
    EDITIOR_CANNOT_HAVE_INPERSON_FIELD,
    MEETING_HOST_CANNOT_HAVE_SIGNATURE_FIELD,
    MEETING_HOST_CANNOT_HAVE_INITIAL_FIELD,

    #endregion AccessManagementErrors

    #region BILLING ERRORS

    BILLING_ERROR_PAYMENT_CANCELLATION_FAILED,
    BILLING_ERROR_PAYMENT_ALREADY_CANCELLED,
    BILLING_PAYMENT_FAILED_MESSAGE,

    #endregion BILLING ERRORS

    #region EnterpriseRoleErrors

    ENTERPRISE_ROLE_ERROR_UNABLE_TO_REMOVE,
    ERROR_ENTERPRISE_ROLE_NOT_ALLOWED,
    ERROR_ENTERPRISE_ROLE_NAME_DOESNOT_EXSIT,
    ENTERPRISE_INTEGRATION_ROLE_ERROR_UNABLE_TO_REMOVE,
    SETTINGS_ROLE_ADD_ERROR_ROLE_EXISTS,
    SETTINGS_ROLE_DELETE_ERROR_DEFAULT,
    ERROR_NO_ROLE_FOR_INDIVIDUAL_USER,
    ROLE_ERROR_CANNOT_CHANGE_OWN_ROLE,
    ROLE_ERROR_CANNOT_REMOVE_OWN_ROLE_RIGHTS,
    ROLE_ERROR_FAULTY_DEFAULT_ROLE_SELECTION,
    SETTINGS_ROLE_DELETE_ERROR_INTEGRATION,
    SETTINGS_ROLE_DELETE_ERROR_DEFAULT_GUEST_USER,
    ENTERPRISE_ROLE_ERROR_DOES_NOT_EXIST,
    SETTINGS_ROLE_DELETE_ERROR_USERS,

    #endregion EnterpriseRoleErrors

    #region ACCOUNT_ERROR

    ACCOUNT_ERROR_REMOVE_ACCOUNT_FAILED,
    ACCOUNT_ERROR_REMOVE_ENTERPRISE_OWNER_FAILED,
    ACCOUNT_REMOVE_ERROR_CHANGE_ENTERPRISE_OWNER,
    ACCOUNT_REMOVE_ERROR_CHILD_USERS_EXIST,
    ACCOUNT_LOCKED_MESSAGE,
    LICENSE_ERROR_DATA_ARCHIVING_NOT_ENABLED,
    ACCOUNT_ARCHIVE_ERROR_CHILD_USERS_EXIST,
    OTP_ERROR_EXPIRY_TIME,

    #endregion ACCOUNT_ERROR

    #region API

    API_ERROR_INTERNAL_SERVER,
    API_ERROR_UNSUPPORTED_CONTENT_TYPE,
    API_ERROR_USER_AUTHENTICATION_REQUIRED,
    API_ERROR_INVALID_TIMEZONE,
    API_ERROR_LANGUAGE_NOT_SUPPORTED,
    API_ERROR_REASON_DOES_NOT_EXIST_IN_PREDEFINED_REASONS,
    API_ERROR_ROLE_DOES_NOT_ALLOW_CUSTOM_REASONS,
    API_ERROR_CHANGE_IN_APPEARANCE_NOT_ALLOWED,
    API_ERROR_INVALID_SIGNATURE_APPEARANCE_OPTION,
    API_ERROR_SIGNATURE_APPEARANCE_OPTION_IS_NOT_ALLOWED,
    API_ERROR_HAND_SIGNATURE_DRAW_FOR_WEB_NOT_ALLOWED,
    API_ERROR_HAND_SIGNATURE_UPLOAD_FOR_WEB_NOT_ALLOWED,
    API_ERROR_HAND_SIGNATURE_TEXT_FOR_WEB_NOT_ALLOWED,
    API_ERROR_HAND_SIGNATURE_DRAW_FOR_MOBILE_NOT_ALLOWED,
    API_ERROR_HAND_SIGNATURE_UPLOAD_FOR_MOBILE_NOT_ALLOWED,
    API_ERROR_INITIALS_NOT_FOUND,
    API_ERROR_HAND_SIGNATURE_TEXT_FOR_MOBILE_NOT_ALLOWED,
    API_ERROR_INITIALS_DRAW_NOT_ALLOWED,
    API_ERROR_INITIALS_UPLOAD_NOT_ALLOWED,
    API_ERROR_INITIALS_TEXT_NOT_ALLOWED,
    API_ERROR_REQUIRED_FEATURES_ARE_NOT_SUPPORTED,
    API_ERROR_AUTHENTICATION_REQUIRED,
    API_ERROR_DOCUMENT_NOT_FOUND,
    API_ERROR_DOCUMENT_NOT_FOUND_IN_LIBRARY,
    API_ERROR_INVALID_DOCUMENT_STATUS,
    API_ERROR_REQUEST_DOES_NOT_CONTAIN_DOCUMENT,
    API_ERROR_DOCUMENT_IMAGE_CREATION,
    API_ERROR_ENTERPRISE_ROLE_INTEGRATION_IS_NOT_ALLOWED,
    API_ERROR_SCOPE_USER_ROLE_MANAGE_USERS_NOT_ALLOWED,
    API_ERROR_SERVICE_PLAN_INTEGRATION_IS_NOT_ALLOWED,
    ENTERPRISE_ERROR_USER_DOES_NOT_BELONG_TO_ENTERPRISE,
    API_ERROR_EMAIL_OR_PASSWORD_INCORRECT,
    ERROR_LOGIN_INCORRECT_CREDENTIALS,
    ERROR_DOCUMENT_PASSWORD_REQUIRED,
    API_ERROR_WORKFLOW_CONTAIN_NO_COLLABORATOR,
    API_ERROR_WORKFLOW_CONTAIN_NO_COLLABORATOR_TASK,
    API_ERROR_WORKFLOW_COLLABORATOR_DOES_NOT_EXIST,
    API_ERROR_WORKFLOW_COLLABORATOR_NOT_VALID,
    API_ERROR_WORKFLOW_PROVIDED_FIELD_TYPE_IS_INVALID,
    API_ERROR_WORKFLOW_TYPE_INDIVIDUAL_CANT_PROCEED,
    API_ERROR_WORKFLOW_COLLABORATOR_ORDER,
    API_ERROR_WORKFLOW_ONLY_SIGNER_CAN_ADD_CURRENT_FIELD_TYPE,
    API_ERROR_WORKFLOW_INDIVIDUAL_UNABLE_TO_ADD_OTP_FOR_ESIGN_AND_INPERSON,
    API_ERROR_WORKFLOW_HOST_CANT_ADD_CURRENT_FIELD_TYPE,
    API_ERROR_WORKFLOW_ONLY_SIGNER_OR_INPERSON_HOST_CAN_ADD_CURRENT_FIELD_TYPE,
    API_ERROR_WORKFLOW_UNABLE_TO_ADD_INITIAL_ON_THIS_DOCUMENT,
    API_ERROR_WORKFLOW_EITHER_ADD_DIGITAL_OR_ELECTRONIC_SIGNATURE,
    API_ERROR_WORKFLOW_MOBILE_NUMBER_EMPTY_OF_COLLABORATOR,
    RADIOBOX_CHECKBOX_ERROR_INVALID_INPUT_VALUE,
    API_ERROR_DOCUMENT_INVALID_DIMENSIONS,
    API_ERROR_DOCUMENT_PERMISSION_PASSWORD_INCORRECT,
    API_ERROR_DOCUMENT_PERMISSION_OTP_ACCESS_NOT_ENABLED,
    API_ERROR_DOCUMENT_IS_NO_LONGER_IN_DRAFT_STATE,
    API_ERROR_DOCUMENT_IS_NOT_IN_SHARED_STATE,
    API_ERROR_RENAME_DOCUMENT,
    API_ERROR_DELETE_DOCUMENT,
    API_ERROR_YOU_ARE_NOT_AUTHORIZED_TO_DELETE_THIS_DOCUMENT,
    API_ERROR_TEMPLATE_NOT_FOUND,
    API_ERROR_PLACEHOLDER_NOT_FOUND,
    API_ERROR_INIVITATION_ENTERPRISE_ADMIN_ROLE_IS_REQUIRED,
    API_ERROR_GET_USER_ROLE,
    API_ERROR_ROLE_NOT_FOUND,
    API_ERROR_INVITATION_NOT_FOUND,
    API_ERROR_DROPBOX_DISABLED,
    API_ERROR_GOOGLE_DISABLED,
    API_ERROR_ONEDRIVE_DISABLED,
    API_ERROR_AUTHENTICATED_USER_CANNOT_BE_DELETED,
    API_ERROR_ENTERPRISE_OWNER_CANNOT_BE_DELETED,
    API_ERROR_USER_IS_NOT_DOCUMENT_OWNER,
    API_ERROR_FIELD_NAME_SAME,
    API_ERROR_FIELD_NAME_INVALID,
    API_ERROR_USERS_SAME_ORDER,
    API_ERROR_GROUPS_SAME_ORDER,
    API_ERROR_SAME_ORDER_FOR_MULTIPLE_SIGNERS,
    API_ERROR_COLLABORATOR_SIGNING_ORDER_IS_GREATER_THAN_COUNT,
    API_ERROR_COLLABORATOR_SIGNING_ORDER_SHOULD_BE_GREATER_THAN_ZERO,
    FIELD_ERROR_INVALID_FONT_INFORMATION,
    FIELD_ERROR_DIMENSIONS_SHOULD_BE_GREATER_THAN_ZERO,
    FIELD_ERROR_QR_CODE_MUST_HAVE_SAME_WIDTH_HEIGHT,
    FIELD_ERROR_QR_CODE_INVALID_DIMENSIONS,
    API_ERROR_COLLABORATOR_SIGNING_POSITION_IS_INVALID,
    API_ERROR_GROUP_NOT_FOUND,
    API_ERROR_SIGNATURE_COUNT_MISMATCH,
    API_ERROR_SIGNATURE_FIELD_NOT_FOUND,
    API_ERROR_FIELD_ALREADY_ASSIGN_TO_SAME_USER,
    API_ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED,
    INITIAL_ERROR_FIELD_DOESNT_EXIST,
    API_ERROR_INPERSON_NOT_FOUND,
    API_ERROR_DOCUMENT_PAGE_NOT_FOUND,
    API_ERROR_PAGE_NUMBER_SHOULD_BE_GREATER_THAN_ZERO,
    API_ERROR_RECORD_PER_PAGE_NUMBER_SHOULD_BE_GREATER_THAN_ZERO,
    API_ERROR_DOCUMENT_IS_NOT_IN_PENDING_STATE,
    API_ERROR_WORKFLOW_COMPLETE_ALL_TASKS,
    FIELD_ERROR_NOT_FOUND,
    API_ERROR_FORM_FIELD_INVALID_FORMAT_TYPE,
    API_ERROR_FORM_FIELD_INVALID_DATE,
    API_ERROR_SETTINGS_ARE_FAULTY,
    API_ERROR_HEADER_INVALID_FILE_NAME,
    API_ERROR_HEADER_FILE_NAME_NOT_FOUND,
    API_ERROR_HEADER_SOURCE_NOT_FOUND,
    API_ERROR_FORM_FIELD_INVALID_VALUE,
    API_ERROR_PERMISSION_LEGAL_NOTICE_NOT_FOUND,
    API_ERROR_DEFAULT_ROLE_NOT_FOUND,
    API_ERROR_OLD_AND_NEW_PASSWORD_IS_SAME,
    API_ERROR_NOT_A_VALID_BASE64_STRING,
    API_ERROR_HAND_SIGNATURE_IMAGE_REQUIRED,
    SIGN_PANEL_ERROR_FILL_INITIAL,
    INTEGRATION_ERROR_USER_ALREADY_EXISTS,
    INTEGRATION_ERROR_ENTERPRISE_ROLE_NOT_EXISTS,
    INTEGRATION_ERROR_USER_NOT_EXISTS,
    INTEGRATION_ERROR_ENTERPRISE_USER_ALREADY_EXISTS,
    ERROR_EMAIL_ADDRESS_INVALID,
    ERROR_ALREADY_CERTIFIED_DOCUMENT,
    ERROR_CERTIFIED_PERMISSION_INVALID,
    ERROR_OLD_PASSWORD_INCORRECT,
    ERROR_PASSWORD_REQUIRED,
    ERROR_OFFICE_SIGNATURE_INVALID_EMAIL,
    ERROR_OFFICE_365_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    ERROR_PARALLEL_SHARE_FEATURE_NOT_AVAILABLE_IN_NATIVE_APPS,
    PROCESS_EVIDENCE_ERROR_NOT_AVAILABLE,
    API_ERROR_FROM_DATE_IS_GREATER_THAN_TO_DATE,
    API_ERROR_NO_CONTACT_ADDED_FOR_POST_PROCESSING,
    API_ERROR_USE_EITHER_BY_DATE_OR_BY_DAYS_OPTION,
    API_ERROR_EITHER_ENABLE_BY_DATE_OR_BY_DAYS_OPTION,
    API_ERROR_EITHER_ENABLE_PASSWORD_OR_SMS_OTP_OPTION,
    API_ERROR_USE_EITHER_PASSWORD_OR_OTP_ACCESS_SECURITY,
    API_ERROR_ORDER_CANNOT_BE_ZERO,
    API_ERROR_DOCUMENT_FIELD_MUST_LOCK_IF_NO_CHANGES_ALLOWED,
    API_ERROR_DOCUMENT_ID_SHOULD_BE_UNIQUE,
    API_ERROR_CANNOT_SORT_ONE_DOCUMENT,
    API_ERROR_ACCESS_DURATION_BY_DAYS_VALUE_SHOULD_BE_LESS_THAN_100,
    EMAIL_MESSAGE_ERROR_LENGTH_EXCEEDS,
    API_ERROR_START_OR_END_DATE_IS_REQUIRED,
    API_ERROR_START_DATE_IS_GREATER_THAN_END_DATE,
    API_ERROR_TOTAL_DAYS_TAG_IS_REQUIRED,
    SETTINGS_PROFILE_ERROR_INVALID_PASSWORD,
    API_ERROR_MAX_VALUE_LENGTH_EXCEEDS,
    FORMFIELD_ERROR_VALIDATION_REQUIRED_VALUE_LENGTH_EXCEEDS,
    API_ERROR_FIELD_ALREADY_PROCESSED,
    API_ERROR_LOG_ID_DOES_NOT_EXIST,
    API_ERROR_OTP_NOT_ALLOWED_IN_USER_ROLE,
    API_ERROR_COLLABORATOR_CANNOT_PERFORM_THIS_ACTION,
    API_ERROR_USER_CANNOT_VIEW_THIS_LOG,
    INTEGRATION_ERROR_ACCESS_TOKEN_INVALID,
    INTEGRATION_REGISTER_ERROR_ACCESS_TOKEN_INVALID,
    API_ERROR_INVALID_LINK,
    ERROR_DIGITAL_SIGNATURE_ALLOWED_ONLY,
    ERROR_ELECTRONIC_SIGNATURE_ALLOWED_ONLY,
    PUSH_NOTIFICATION_ERROR_UNABLE_TO_ADD_DEVICE,
    ACTIVITY_LOG_ERROR_LOG_NOT_AVAILABLE,
    REFRESH_TOKEN_ERROR_AUTHENTICATION_REQUIRED,
    AUTHENTICAION_ERROR_CLIENT_CERTIFICATE_REQUIRED,
    API_ERROR_ADMIN_AUTHENTICATION_REQUIRED,
    SERVICE_PLAN_ERROR_NOT_FOUND,
    PUSH_NOTIFICATION_ERROR_INVALID_OS_TYPE,
    API_INVALID_CERTIFICATION_CAPACITY_NAME,
    API_ERROR_SIGNATURE_SETTING_FAULTY_SIGNING_CAPACITY,
    API_ERROR_BASE64_NOT_FOUND,
    API_ERROR_USER_SETTING_NOT_FOUND,
    API_ERROR_ENCRYPTED_KEY_NOT_FOUND,
    API_ERROR_AUTO_PLACE_TEXT_NOT_FOUND,
    API_ERROR_AUTO_PLACE_FIELD_TYPE_NOT_CORRECT,
    API_ERROR_AUTO_PLACE_NO_SEARCH_TEXT,
    API_ERROR_AUTO_PLACE_FIELD_PLACE_HOLDER_NOT_PROVIDED,
    API_ERROR_AUTO_PLACE_FIELD_PLACEMENT_VALUE_NOT_CORRECT,
    API_ERROR_CHANGE_RECIPIENT_NOT_ALLOWED_IN_ROLE,
    ERROR_USER_IDENTITY_ALREADY_EXISTS,
    ERROR_USER_IDENTITY_KEY_INVALID,
    API_ERROR_SCOPE_LOGIN_INCORRECT_CREDENTIALS,
    API_ERROR_DOCUMENT_SIGNING_NOT_ALLOWED,
    DRAFT_PANEL_PERMISSIONS_ERROR_TILL_DATE_SMALLER,
    API_ERROR_DOCUMENT_APPROVING_NOT_ALLOWED,
    API_ERROR_CANNOT_SHARE_DOCUMENT_PACKAGE,
    API_ERROR_ACCESS_DURATION_BY_DAYS_VALUE_SHOULD_BE_GREATER_THAN_ZERO,
    API_ERROR_SIGNATURE_DISPLAY_TYPE_INVALID,
    API_ERROR_TEMPLATE_PRIVATE,
    API_ERROR_AUTO_PLACE_FIELD_GROUP_NAME_NOT_PROVIDED,
    API_ERROR_ENTERPRISE_SETTINGS_ACCOUNT_CAPACITY_NAME_ALREADY_EXIST,
    API_ATTACHMENT_PERMISSION_ERROR_REQUIRED_NOTE_IS_NULL_OR_EMPTY,

    #endregion API

    #region ADMINISTRATION

    ADMINISTRATION_ERROR_SEARCH_WITH_SAME_NAME_ALREADY_EXIST,
    INVALID_ADMIN,
    CONFIGURATIONS_ACCESS_CONTROL_CERTIFICATE_ALREADY_EXIST,
    CONFIGURATIONS_ACCESS_CONTROL_EMAIL_ALREADY_EXIST,
    CERTIFICATE_ERROR_EXPIRED,
    CERTIFICATE_ERROR_INVALID,
    ERROR_ACCOUNTS_REGISTER_EMAIL_NOT_AVAILABLE,
    ERROR_ROLE_NAME_EXIST,
    CONFIGURATIONS_ACCESS_CONTROL_CANNOT_CHANGE_OWN_ROLE,

    #endregion ADMINISTRATION

    #region ACTIVE DIRECTORY

    ERROR_AD_VALIDATION_FAILED,
    ERROR_AD_ACCESS_NOT_ALLOWED,
    ERROR_AD_EMAIL_NOT_AVAILABLE,
    ERROR_AD_AUTH_PROFILE_SECURITY_GROUP_IS_ALREADY_CONFIGURED,
    ERROR_AD_PROVISIONING_NOT_FOUND,
    ERROR_AD_USER_IS_NOT_VALID_SECURITY_GROUP_MEMBER,
    ERROR_AD_PROVISIONING_MAPPING_ADD_FAILED,
    ERROR_AD_PROVISIONING_AUTH_GROUPS_FETCH_FAILED,
    ACTIVE_DIRECTORY_ERROR_PROFILE_NOT_FOUND,
    ACTIVE_DIRECTORY_ERROR_CONNECTOR_INACTIVE,

    #endregion ACTIVE DIRECTORY

    #region ACTIVE DIRECTORY FEDRATION SERVICES

    ERROR_ADFS_ACCESS_NOT_ALLOWED,
    ERROR_ADFS_EMAIL_NOT_AVAILABLE,

    #endregion ACTIVE DIRECTORY FEDRATION SERVICES

    #region AdministratorRole Error

    ERROR_ROLE_DELETE_USERS,

    #endregion AdministratorRole Error

    #region Role Deny Key

    ROLE_ERROR_DENY_ACCESS,
    ROLE_ERROR_DEFAULT_APPEARANCE_NOT_ALLOWED,

    #endregion Role Deny Key

    #region SAML

    SAML_ERROR_IDP_META_DATA_INVALID,
    SAML_ERROR_IDP_CERTIFICATE_NOT_TRUSTED,
    SAML_ERROR_IDP_DOES_NOT_SUPPORT_IDENTIFIER_EMAIL_ADDRESS,
    SAML_ERROR_INVALID_SIGNATURE,
    SAML_ERROR_FAILED_TO_GET_USER_PROFILE_INFORMATION,

    #endregion SAML

    #region COLLABORATOR

    COLLABORATOR_ERROR_SIGNING_ORDER_IS_NOT_UNIQUE,
    COLLABORATOR_ERROR_NOT_VALID_TYPE,
    ERROR_COLLABORATOR_IS_NOT_PART_OF_ENTERPRISE,
    ERROR_DELEGATED_USER_IS_NOT_PART_OF_ENTERPRISE,
    ERROR_DELEGATE_USER_IS_NOT_PART_OF_ENTERPRISE,
    API_ERROR_CANNOT_SORT_ONE_COLLABORATOR,
    ERROR_COLLABORATOR_NOT_FOUND,

    #endregion COLLABORATOR

    #region START NEW WORKFLOW

    START_NEW_WORKFLOW_DOWNLOAD_ERROR_PERMISSION,
    START_NEW_WORKFLOW_ERROR_ACCESS_DURATION_TIME_NOT_STARTED,
    START_NEW_WORKFLOW_ERROR_ACCESS_DURATION_EXPIRES,
    START_NEW_WORKFLOW_DOWNLOAD_ERROR_DELEGATION_TIME_NOT_STARTED,
    START_NEW_WORKFLOW_DOWNLOAD_ERROR_DELEGATION_TIME_EXPIRES,
    START_NEW_WORKFLOW_DOWNLOAD_ERROR_OTP_PASSWORD,
    START_NEW_WORKFLOW_DOWNLOAD_ERROR_PASSWORD,
    ERROR_DRAFT_COMPLETE_INITIALS_BEFORE_SUBMITTING,
    ERROR_DRAFT_COMPLETE_INITIALS_BEFORE_SHARING,
    ERROR_DRAFT_COMPLETE_INPERSONS_BEFORE_SHARING,
    ERROR_DRAFT_COMPLETE_HAND_SIGNATURES_BEFORE_SHARING,
    ERROR_DRAFT_COMPLETE_INITIALS_BEFORE_SIGNING,
    ERROR_DRAFT_COMPLETE_INPERSONS_BEFORE_SIGNING,
    ERROR_DRAFT_COMPLETE_HAND_SIGNATURES_BEFORE_SIGNING,
    ERROR_DRAFT_SIGNER_ADD_TASK_FOR_EDITOR,

    #endregion START NEW WORKFLOW

    #region BULK SIGNING

    ERROR_BULK_SIGN_DOCUMENT_STATUS_INCORRECT,
    ERROR_BULK_SIGN_DOCUMENT_ACCESS_PASSWORD_PERMISSION,
    ERROR_BULK_SIGN_DOCUMENT_ACCESS_OTP_PERMISSION,
    ERROR_BULK_SIGN_DOCUMENT_HAS_UNPROCESSED_SUBTASKS,
    ERROR_SIGNATURE_FIELD_HAS_OTP_AUTHENTICATION,
    BULK_SIGN_ERROR_AGREE_LEGAL_NOTICE,

    #endregion BULK SIGNING

    #region Custom Folder

    FOLDER_ERROR_NAME_ALREADY_EXISTS,
    FOLDER_ERROR_NOT_EMPTY,

    #endregion Custom Folder

    #region REMOTE AUTHORIZATION

    REMOTE_AUTHORIZED_SIGNING_ERROR_NOT_ALLOWED_IN_ROLE,
    REMOTE_AUTHORIZED_SIGNING_ERROR_TIME_LIMIT_REACHED,
    REMOTE_AUTHORIZED_SIGNING_ERROR_REQUEST_NOT_FOUND,
    REMOTE_AUTHORIZE_SIGNING_ERROR_DEVICE_MISSING,
    REMOTE_AUTHORIZE_SIGNING_ERROR_REQUEST_DECLINED,
    BULK_SIGN_AND_SHARE_ERROR_REMOTE_AUTHORIZE_SIGNING_NOT_ALLOWED,

    #endregion REMOTE AUTHORIZATION

    #region Formfields Error

    FORM_FIELD_ERROR_DATE_FORMAT_NOT_SUPPORTED,
    ERROR_DATE_VALUE_NOT_ACCORDING_TO_FORMAT,
    ERROR_TIME_VALUE_NOT_ACCORDING_TO_FORMAT,

    #endregion Formfields Error

    PERMISSION_ERROR_CANNOT_SET_OTP_FOR_ALL_RECIPIENTS,

    INITIAL_ERROR_ALREADY_PROCESSED,
    WEB_SERVICE_ERROR_EXPIRY_LESSTHAN_ACCESS,
    SEND_REMINDER_EMAIL_FAILURE_MESSAGE,
    CONTACT_DOESNOT_EXISTS,
    CERTIFICATE_DOESNOT_EXISTS,
    ERROR_CERTIFICATE_ALIAS_IS_NOT_VALID,
    ERROR_CERTIFICATE_FRIENDLY_NAME_IS_NOT_VALID,
    CERTIFICATE_FRIENDLY_NAME_ERROR_ALREADY_EXIST,

    #region VERISEC MOBILE

    #region FREJA MOBILE

    VERISEC_MOBILE_ERROR_REQUEST_CANCELLED,
    VERISEC_MOBILE_ERROR_REQUEST_TIME_OUT,
    VERISEC_MOBILE_ERROR_REQUEST_NOT_PROVISIONED,
    VERISEC_MOBILE_ERROR_REQUEST_FAILED,
    VERISEC_MOBILE_ERROR_USER_NOT_AVAILABLE,

    #endregion FREJA MOBILE

    VERISEC_EID_ERROR_INVALID_OR_MISSING_USER_INFO_TYPE,
    VERISEC_EID_ERROR_INVALID_OR_MISSING_USER_INFO,
    VERISEC_EID_ERROR_USER_INFO_NOT_COMPATIBLE_WITH_USER_INFO_TYPE,
    VERISEC_EID_ERROR_INVALID_RESTRICT,
    VERISEC_EID_ERROR_AUTH_REQUEST_FAILED_SECURITY_REASON,
    VERISEC_EID_ERROR_USER_NOT_ALLOWED_TO_CALL_THIS_METHOD,
    VERISEC_EID_ERROR_SERVICE_NOT_ENABLED,
    VERISEC_EID_ERROR_SSN_REQUIRED,
    VERISEC_EID_ERROR_PREVIOUS_CALL_WAS_NOT_COMPLETED,
    VERISEC_EID_ERROR_REQUEST_CANCELLED,
    VERISEC_EID_ERROR_REQUEST_TIME_OUT,
    VERISEC_EID_ERROR_REQUEST_REJECTED,

    VERISEC_EID_ERROR_INVALID_REGISTRATION_MIN_LEVEL,
    VERISEC_EID_ERROR_INVALID_REFERENCE,

    #endregion VERISEC MOBILE

    #region Document Storage

    DATA_DIRECTORY_DOCUMENTS_DOES_NOT_EXIST,
    CONFIGURATIONS_DATA_DIRECTORY_ERROR_NO_ACCESS_RIGHTS,
    CONFIGURATIONS_DATA_DIRECTORY_ERROR_INVALID_PATH,

    #endregion Document Storage

    #region DOCUMENT SECURITY

    CONFIGURATIONS_DATA_SECURITY_ERROR_ENCRYPTION_FAILED,
    CONFIGURATIONS_DATA_SECURITY_ERROR_DECRYPTION_FAILED,

    #endregion DOCUMENT SECURITY

    #region DATA ARCHIVE

    CONFIGURATIONS_DATA_ARCHIVING_ERROR_INVALID_PATH,
    CONFIGURATIONS_DATA_ARCHIVING_ERROR_NO_ACCESS_RIGHTS,
    ACCOUNTS_ARCHIVE_ERROR_INVALID_DOCUMENT,
    ACCOUNTS_ARCHIVE_ERROR_INVALID_EVIDENCE_REPORT,

    #endregion DATA ARCHIVE

    #region SIGNALR

    CONFIGURATIONS_REDIS_ERROR_FAILED_LOGIN,

    #endregion SIGNALR

    APPLICATION_NAME_AND_KEY_ALREADY_EXISTS,
    INTEGRATION_ERROR_APPLICATION_KEY_NOT_EXIST,
    SETTINGS_GROUP_ALREADY_EXISTS,

    ROLE_ERROR_MANAGE_PROFILE_RIGHTS,
    ENTERPRISE_ERROR_SLUG_EXISTS,
    SERVICE_PLAN_ERROR_PLAN_ALREADY_EXIST,
    DOCUMENT_ERROR_EMPTY_CONTENT,
    SIGN_ACCESS_MANAGMENT_WARNING_SIGNATURE,
    WORKFLOW_MODE_ERROR_ONLY_ME,
    WORKFLOW_MODE_ERROR_ONLY_ME_MULTIPLE_RECIPIENTS,
    WORKFLOW_MODE_ERROR_ONLY_ME_LOGGEDIN_USER,
    WORKFLOW_MODE_ERROR_ONLY_ME_SIGNER_TYPE,
    WORKFLOW_MODE_ERROR_ONLY_ME_CERTIFY_AND_LOCK,

    #region Terms And Conditions

    TERMS_SERVICES_ERROR_REMOVE_ACTIVE,
    LOGIN_ERROR_TERM_AND_CONDITION_AGREE_REQUIRED,
    TERMS_SERVICES_ERROR_DEFAULT_SELECTION,

    #endregion Terms And Conditions

    #region Legal Notice

    ENTERPRISE_SETTINGS_DEFAULT_LEGAL_NOTICE_DELETE_ERROR,
    ERROR_LEGAL_NOTICE_NOT_FOUND,

    #endregion Legal Notice

    SIGNING_ERROR_RUT_REQUIRED,

    #region RA

    RA_ERROR_INVALID_MOBILE_NUMBER,
    RA_ERROR_REGISTER_USER_FAILED,
    BANKID_ERROR_FAILED_TO_GET_USER_PROFILE_INFORMATION,

    #endregion RA

    DRAFT_PANEL_PERMISSIONS_ERROR_DURANTION_REQUIRED,
    REMOTE_AUTHORIZED_ERROR_REGISTER_RA_USER_FAILED,
    SIGN_ERROR_REMOTE_AUTHORIZATION_FAILED,
    COMMON_ERROR_INVALID_OPERATION,
    ERROR_INVISIBLE_SIGNATURES_VALIDATION,
    ERROR_REGISTRATION_NOT_ALLOWED,
    ERROR_USER_MUST_CHANGE_PASSWORD,
    COMMON_PAGE_EXPIRED_LINK_ERROR,
    API_ERROR_LOGIN_RESET_PASSWORD_REQUIRED,
    BULK_SIGN_DOCUMENT_OTP_ERROR,
    BULK_SIGN_ERROR_DOCUMENT_TYPE_WORD,
    BULK_SIGN_ERROR_ACCESS_DURATION_TIME_EXPIRED,
    BULK_SIGN_ERROR_DELEGATION_TIME_NOT_STARTED,
    BULK_SIGN_ERROR_AUTHENTICATION_PASSWORD,
    BULK_SIGN_ERROR_AUTHENTICATION_OTP,
    BULK_SIGN_ERROR_AUTHENTICATION_SIGNING_OTP,
    BULK_SIGN_ERROR_REQUIRED_FORM_FIELD,
    DOCUMENT_ERROR_MIXED_EXTENSIONS_NOT_ALLOWED,
    XML_WORKFLOW_ERROR_SIGNER_TYPE_INVALID,
    WORKFLOW_ERROR_FIELD_TYPE_NOT_VALID,
    XML_WORKFLOW_ERROR_CANNOT_ADD_DUPLICATE_FIELD,
    XML_API_ERROR_TEMPLATE_CANNOT_BE_APPLIED_ON_DOCUMENT,
    XML_SIGNING_ERROR_LOCAL_SIGNING_NOT_ALLOWED,
    XML_PERMISSION_ERROR_CANNOT_SET_ATTACHMENT_FOR_DOCUMENT,
    DOCX_PERMISSION_ERROR_CANNOT_SET_ATTACHMENT_FOR_DOCUMENT,
    DOCX_PERMISSION_ERROR_CANNOT_SET_ON_PAGE_COMMENT,
    NON_PDF_ERROR_CERTIFY_POLICY_CANNOT_BE_APPLIED,
    XML_PERMISSION_ERROR_CANNOT_SET_ON_PAGE_COMMENT,
    XML_API_ERROR_DOCUMENT_INVALID,
    COMMON_ERROR_HTML_INJECTION_EMPTY_VALUE,
    ITSME_AUTHENTICTION_ERROR_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    ITSME_AUTHENTICATION_ERROR_REQUEST_CANCELLED,
    ITSME_AUTHENTICATION_ERROR_REQUEST_TIME_OUT,
    ITSME_AUTHENTICATION_ERROR_INVALID_TOKEN,
    ITSME_AUTHENTICATION_ERROR_TRANSACTION_FAILED,
    ITSME_AUTHENTICATION_ERROR_INVALID_PARAMETERS,
    ERROR_USER_PASSWORD_EXPIRED,

    //CSP ERROR
    VIRTUAL_ID_ERROR_CONFIGURATIONS_INCORRECT,

    SHARED_SPACE_COLLABORATORS_UNIQUE_ERROR,
    SHARED_SPACE_MOVE_ITEMS_ERROR,
    SHARED_SPACE_LOGGED_IN_USER_ERROR,
    SHARED_SPACE_ERROR_NAME_IS_REQUIRED,
    SHARED_SPACE_ERROR_DOES_NOT_EXIST,
    SHARED_SPACE_ERROR_ATLEAST_ONE_MEMBER_IS_REQUIRED,
    SHARED_SPACE_ERROR_ALREADY_EXIST,
    ACCOUNT_ERROR_FOLDER_NAME_DOES_NOT_EXIST,

    //ERRORS FOR CERTIFIED AND LOCKED
    VIEWER_ERROR_DRAFT_SIGNER_TASK_PROCESSED_CERTIFIED,

    VIEWER_ERROR_DRAFT_DOCUMENT_LOCKED,
    DOCUMENT_CERTIFY_WITH_FORM_FILLING_ONLY,
    API_ERROR_ONLY_XML_DOCUMENT_ALLOWED,
    API_ERROR_ONLY_WORD_DOCUMENT_ALLOWED,
    VIEWER_ERROR_DOCUMENT_LOCKED_BY_OTHER_RECIPIENT,

    //FILE SCANNING ERROR
    COMMON_ERROR_FILE_SCAN_INFECTED,

    USER_ACCESSLEVEL_DISABLE_SUCCESS,

    COMMON_ERROR_IS_NULL_OR_EMPTY,
    COMMON_ERROR_LENGTH_IS_INVALID,
    SIGNING_METHOD_FAULTY_CONFIGURATION,
    API_ERROR_SIGNING_SERVER_FAULTY_CONFIGURATION,
    ERROR_SIGN_EMAIL_NOT_MATCH_WITH_LOGIN,
    LEVEL_OF_ASSURANCE_ERROR_REQUIRED,
    LEVEL_OF_ASSURANCE_ERROR_INVALID,

    #region Level Of Assurance

    LEVEL_OF_ASSURANCE_ERROR_NOT_ALLOWED,
    SIGN_ERROR_CAPACITY_DOES_NOT_MATCH_WITH_LEVEL_OF_ASSURANCE,

    #endregion Level Of Assurance

    SIGN_ERROR_SIGNING_SERVER_REQUIRED,
    SIGN_ERROR_CAPACITY_REQUIRED,
    SIGN_ERROR_CAPACITY_NOT_AVAILABLE_WITH_LEVEL_OF_ASSURANCE,
    CSC_ERROR_ONLY_PDF_SIGNING_ALLOWED,
    CSC_ERROR_ESEAL_NOT_ALLOWED,
    CSC_AUTHORIZATION_REQUEST_CANCELED,
    CSC_ERROR_DUPLICATE_CUSTOM_PARAMS_KEY,
    SIGNING_ERROR_INVALID_CSC_SERVER_PROVIDED,
    SIGN_ERROR_CAPACITY_NOT_ALLOWED_IN_ROLE,
    SIGN_ERROR_SIGNING_SERVER_NOT_ALLOWED_IN_ROLE,
    SIGN_ERROR_SIGNING_SERVER_NOT_ALLOWED_IN_SERVICE_PLAN,
    SIGN_BULK_ERROR_DOCUMENT_HAS_MULTIPLE_SIGNATURES,

    ENTERPRISE_ERROR_USER_IS_NOT_PART_OF_ENTERPRISE,
    VIEWER_ERROR_FIELD_NOT_ASSIGNED,
    DRAFT_SIGNING_ERROR_INDIVIDUAL_WORKFLOW,
    FIELD_DIMENSIONS_SHOULD_BE_GREATER_THAN_ZERO,
    LOGIN_ERROR_USER_IS_NOT_REGISTERED,
    API_ERROR_MAX_LENGTH_VALUE_INVALID,
    API_ERROR_INVALID_CHARACTER_LENGTH,
    GOOGLE_ERROR_AUTHENTICATION_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    SIGN_ERROR_AUTHENTICATION_ACCESS_TOKEN_REQUIRED,
    SIGN_ERROR_AUTHENTICATION_MECHANISM_REQUIRED,
    SIGN_ERROR_AUTHENTICATION_MECHANISM_INAVLID,
    SIGN_ERROR_AUTHENTICATION_REQUIRED,
    SIGN_ERROR_AUTHENTICATION_USER_EMAIL_REQUIRED,
    OFFICE_365_ERROR_AUTHENTICATION_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    AZURE_ACTIVE_DIRECTORY_ERROR_AUTHENTICATION_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    LINKED_IN_ERROR_AUTHENTICATION_FAILED_TO_GET_USER_PROFILE_INFORMATION,
    SIGN_ERROR_AUTHENTICATION_MECHANISM_NOT_ALLOWED,
    BULK_SIGN_ERROR_NOT_ALLOWED_IN_SERVICE_PLAN,
    ERROR_RADIO_BUTTON_SAME_GROUP_ASSIGNMENT,
    DOCUMENT_ERROR_PDF_COMPLIANCE_VALIDATION_FAILED,
    FIELD_ERROR_NOT_BELONG_TO_DOCUMENT,
    PDFA_UPLOAD_ERROR_SIGNED_DOCUMENT_NOT_ALLOWED,
    OTP_AUTHENTICATION_MOBILE_NUMBER_MISMATCHED,
    OTP_AUTHENTICATION_MOBILE_NUMBER_EMPTY,
    ATTACHMENT_ERROR_DOES_NOT_EXIST,
    ATTACHMENT_ERROR_NOT_ALLOWED_FOR_NON_PDF,
    SERVICE_PLAN_ERROR_WORKFLOW_EVIDENCE_REPORT_NOT_ALLOWED,
    WORKFLOW_EVIDENCE_REPORT_ERROR_NOT_GENERATED,
    LEVEL_OF_ASSURANCE_ERROR_NOT_VALID_FOR_NON_PDF,
    LEVEL_OF_ASSURANCE_ERROR_NOT_SUPPORTED_WITH_OTHERS,

    //If admin password is invalid
    LOGIN_PASSWORD_INVALID,
    CHANGE_PASSWORD_INVALID_PASSWORD,

    DOWNLOAD_ERROR_ONLY_COMPLETED_PACKAGE,
    FORMFIELD_ERROR_VALIDATION_REQUIRED_VALUE,
    ACCOUNT_ERROR_FOLDER_NAME_IS_REQUIRED,
    ACCOUNT_ERROR_FOLDER_DOES_NOT_EXIST,
    PACKAGE_ERROR_NOT_BELONG_TO_USER,
    ACCOUNT_ERROR_FAILED_TO_MOVE_PACKAGE,
    ACCOUNT_ERROR_TARGET_AND_SOURCE_FOLDERS_ARE_SAME,
    SIGNING_ERROR_NO_CERTIFICATE_FOUND,
    ATTACHMENT_ERROR_NOT_ALLOWED_FOR_PDFA1,
    SERVICE_AGREEMENT_ERROR_ALREADY_IN_USE,
    CONFIGURATION_TERMS_OF_SERVICE_ERROR_SERVICE_AGREEMENT_INACTIVE,
    TERMS_SERVICES_DISABLE_ERROR_ENSURE_AGREEMENT_IS_ENABLED,
    ENSURE_AGREEMENT_ERROR_SERVICE_AGREEMENTS_ARE_DISABLED,
    ERROR_INVALID_CAPTCHA,
    ERROR_SUPPORTED_LANGUAGE_NOT_AVAILABLE,
    INSTANCES_ERROR_STOPPED_INSTANCE_CAN_BE_DELETED,
    ATTACHMENT_ERROR_NOT_ALLOWED_FOR_PDFA_NON_DRAFT,
    PACKAGE_ERROR_PACKAGE_RENAME_NOT_ALLOWED_AFTER_COMPLETION,
    ATTACHMENT_ERROR_NOT_ALLOWED_TO_DELETE,
    WORKFLOW_ERROR_ATTACHMENTS_NOT_ALLOWED_WITH_MULTIPLE_DIGITAL_SIGNATURES,
    WORKFLOW_ERROR_ATTACHMENTS_NOT_ALLOWED_IN_PDFA_COMPLIANT_DOCUMENT,
    WORKFLOW_ERROR_ATTACHMENTS_NOT_ALLOWED_IN_SIGNED_DOCUMENT,
}
