namespace Application.Commands.Common.Enumerations;

public enum AccessControlEnums
{
    ADMIN_LOG
}

public enum AdminLogAction
{
    LOGGED_OUT, LOGGED_IN, ADMIN_ACTIVITY_ADDED, ADMIN_ACTIVITY_UPDATED, ADMIN_ACTIVITY_DOWNLOADED, ADMIN_ACTIVITY_DELETED, COMMON_RESET,
    ADMIN_ACTIVITY_CHANGE_PASSWORD, ADMIN_ACTIVITY_PUBLISH_CHANGES, ADMIN_ACTIVITY_RESET_SERVICE_PLAN, LOG_ACTIVITY_ACTION_RESET_BRANDING,
    LOG_REQUESTED_PASSWORD_CHANGE, ADMIN_ACTIVITY_MODULE_PASSWORD_UPDATE, ADMIN_TERMS_AND_CONDITIONS_ADDED, ADMIN_TERMS_AND_CONDITIONS_UPDATED, ADMIN_TERMS_AND_CONDITIONS_DELETED,
    ADMIN_ACTIVITY_USER_ACCOUNT_UNLOCKED, COMMON_ACTIVITY_CLONED, COMMON_REVOKE, ADMIN_ACTIVITY_DORMANT, ADMIN_ACTIVITY_ARCHIVED
}

public enum AdminLogModule
{
    ADMIN_ACTIVITY_MODULE_PROFILE, ADMIN_ACTIVITY_MODULE_ACCOUNTS, NULL, ADMIN_ACTIVITY_MODULE_CONFIGURATIONS,
    ADMIN_ACTIVITY_MODULE_SERVICE_PLAN, ADMIN_ACTIVITY_MODULE_ACCESS_CONTROL, ADMIN_ACTIVITY_MODULE_BILLINGS, MAIN_REPORTS,
    ADMIN_ACTIVITY_MODULE_AUTHENTICATE, ADMIN_ACTIVITY_MODULE_LOGS, ADMIN_ACTIVITY_SUB_MODULE_OPERATOR
}

public enum AdminRightEnums
{
    Read,
    AddUpdate,
    Delete
}

public enum LogDetail
{
    COMMON_EMAIL_ADDRESS, IP_ADDRESS, SYSTEM, COMMON_NAME, COMMON_PRIVATE, ADMIN_ACTIVITY_DETAILS_PROVIDERS, CONFIGURATIONS_CONNECTORS_PURPOSE,
    ADMIN_ACTIVITY_DETAILS_DESCRIPTION, ROLE_ALLOW_READ, ROLE_ALLOW_ADD_EDIT, ROLE_ALLOW_DELETE, COMMON_MOBILE_NUMBER,
    COMMON_ACTIVE, ADMIN_ACTIVITY_DETAIL_ACCOUNT_TYPE, SERVICE_PLAN_TYPE_ENTERPRISE, SERVICE_PLAN_TYPE_INDIVIDUAL,
    ADMIN_ACTIVITY_DETAIL_STORAGE, COMMON_UNLIMITED, ADMIN_ACTIVITY_DETAIL_SIGNATURES, ADMIN_ACTIVITY_DETAIL_WORK_FLOWS,
    ADMIN_ACTIVITY_DETAIL_TEMPLATES, ADMIN_ACTIVITY_DETAIL_USERS, ADMIN_ACTIVITY_DETAIL_DOCUMENT_UPLOAD_SIZE, ADMIN_ACTIVITY_DETAIL_PAYMENT_TYPE,
    PAY_REGULARLY, PAY_AS_YOU_GO, ADMIN_ACTIVITY_DETAIL_SERVICE_PLAN_FEATURE, ADMIN_ACTIVITY_OLD_SERVICE_PLAN, USER_ACCESSLEVEL_ENABLED,
    ACCOUNT_CERTIFICATE_ALIAS, AUTHENTICATION_PROFILE_VERIFY_SSL, SIGNATURES_LOCAL, SIGNATURES_MOBILE, SIGNATURES_SERVER,
    ADMIN_ACTIVITY_DETAIL_OLD_OPERATOR_LOG_NAME,
    ADMIN_ACTIVITY_DETAIL_USER_STATUS, ADMIN_ACTIVITY_DETAIL_USER_REGISTERED, ADMIN_ACTIVITY_DETAIL_USER_ACTIVATED, ADMIN_ACTIVITY_DETAIL_USER_UPDATED
}

public enum LogInformationKey
{
    ADMIN_ACTIVITY_INFORMATION_SESSION_DURATION, COMMON_NAME, ADMIN_ACTIVITY_INFORMATION_ACCOUNT_OWNER_EMAIL,
    COMMON_EMAIL_ADDRESS, COMMON_ROLE_NAME, COMMON_GROUP_NAME, CONFIGURATIONS_ACCESS_CONTROL_CERTIFICATE
}

public enum LogSubModule
{
    NULL, ADMIN_ACTIVITY_SUB_MODULE_GENERAL_SETTINGS, ADMIN_ACTIVITY_SUB_MODULE_CONNECTORS,
    ADMIN_ACTIVITY_SUB_MODULE_AUTHENTICATION_PROFILES, ADMIN_ACTIVITY_SUB_MODULE_CERTIFICATIONS,
    ADMIN_ACTIVITY_SUB_MODULE_SIGNING_PROFILES, ADMIN_ACTIVITY_SUB_MODULE_VERIFICATIONS_PROFILES,
    ADMIN_ACTIVITY_SUB_MODULE_EVIDENCE_REPORT, ADMIN_ACTIVITY_SUB_MODULE_BILLING, ADMIN_ACTIVITY_SUB_MODULE_BRANDING,
    ADMIN_ACTIVITY_SUB_MODULE_LICENSE, ADMIN_ACTIVITY_SUB_MODULE_ROLE, ADMIN_ACTIVITY_SUB_MODULE_SEARCH,
    ADMIN_ACTIVITY_SUB_MODULE_MANUAL_PAYMENT, ADMIN_ACTIVITY_SUB_MODULE_SERVICE_PLANS,
    ADMIN_ACTIVITY_SUB_MODULE_PROFILE, ADMIN_ACTIVITY_SUB_MODULE_ADMINISTRATOR, ADMIN_ACTIVITY_SUB_MODULE_DATA_DIRECTORY,
    ADMIN_ACTIVITY_SUB_MODULE_INSTANCES,
    ADMIN_ACTIVITY_SUB_MODULE_OPERATOR, ADMIN_ACTIVITY_SUB_MODULE_DATA_SECURITY,
    ADMIN_ACTIVITY_SUB_MODULE_DOMAINS,
    ADMIN_ACTIVITY_SUB_MODULE_TERMS_AND_CONDITIONS, ADMIN_ACTIVITY_SUB_MODULE_REDIS, ADMIN_ACTIVITY_SUB_MODULE_VIRTUAL_PROFILES,

    REPORTS_DOCUMENT_STATISTICS,
    REPORTS_SIGNATURE_STATISTICS,
    REPORTS_SMS_COMSUMED_STATISTICS,
    REPORTS_ACCOUNT_SEARCH_REGISTRATIONS,
    REPORTS_ACCOUNT_SEARCH_LOGIN,
    REPORTS_ACCOUNT_SEARCH_WORKFLOWS,
    REPORTS_ACCOUNT_SEARCH_SIGNATURES,
    REPORTS_BILLING_TITLE,
    REPORTS_SERVICEPLAN_TITLE,
    ACCOUNTS_USER_CERTIFICATE_INFORMATION
}

public enum SearchSection
{
    ACCOUNT = 0,
    BILLING = 1,
    LOG = 2,
    ACCOUNT_REPORT = 4
}

public enum SettingsSection
{
    DOCUMENT,
    GLOBAL,
    DATA_SETTING,
    BILLING,
    WORKFLOW_EVIDENCE_REPORT,
    REDIS,
    EXCLUDED_DOMAINS
}

public enum Flag
{
    [StringValue("False")]
    FALSE = 0,

    [StringValue("True")]
    TRUE = 1
}