#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["ApiGateways/Web.Admin/Web.Admin.GW/Web.Admin.GW.csproj", "ApiGateways/Web.Admin/Web.Admin.GW/"]
RUN dotnet restore "ApiGateways/Web.Admin/Web.Admin.GW/Web.Admin.GW.csproj"
COPY . .
WORKDIR "/src/ApiGateways/Web.Admin/Web.Admin.GW"
RUN dotnet build "Web.Admin.GW.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Web.Admin.GW.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=publish /app/publish/Certs/https/aspnetapp.pfx /https/
ENTRYPOINT ["dotnet", "Web.Admin.GW.dll"]