using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Queries.Common.Enumerations;
public enum AccessControlEnums
{
    ACCOUNT,
    BILLING,
    ACCESS_CONTROL,
    CONNECTOR,
    BRANDING,
    SERVICE_PLAN,
    AUTHENTICATION_PROFILE,
    CERTIFICATION_PROFILE,
    VERIFICATION_PROFILE,
    SIGNING_PROFILE,
    LICENSE,
    PROCESS_EVIDENCE,
    BILLING_SETTING,
    GLOBAL_SETTING,
    DATA_DIRECTORY,
    DATA_SECURITY,
    REPORTS,
    CONFIGURATION_INSTANCES,
    ADMIN_LOG,
    CONFIGURATION_TERMS_SERVICES,
    SIGNALR,
    VIRTUAL_ID_PROFILE
}

public enum SettingsSection
{
    DOCUMENT,
    GLOBAL,
    DATA_SETTING,
    BILLING,
    WORKFLOW_EVIDENCE_REPORT,
    REDIS,
    EXCLUDED_DOMAINS
}

public enum AccessRightName
{
    SHARE_DOCUMENT,
    LOCAL_SIGN,
    SERVER_SIGN,
    MOBILE_SIGN,
    MSSP,
    OTP,
    REMOTE_SIGNING,
    HAND_SIGNATURE_DRAW_FOR_WEB,
    HAND_SIGNATURE_DRAW_FOR_MOBILE,
    HAND_SIGNATURE_TEXT_FOR_WEB,
    HAND_SIGNATURE_TEXT_FOR_MOBILE,
    DISABLE_HAND_SIGNATURE_TEXT_FOR_WEB,
    DISABLE_HAND_SIGNATURE_TEXT_FOR_MOBILE,
    HAND_SIGNATURE_UPLOAD_FOR_WEB,
    HAND_SIGNATURE_UPLOAD_FOR_MOBILE,
    WEB_SERVER_ENABLED,
    WEB_LOCAL_ENABLED,

    //MOBILE_SERVER_ENABLED,
    //MOBILE_SIGN_FOR_MOBILE,
    INITIALS_DRAW,

    INITIALS_TEXT,
    DISABLE_INITIALS_TEXT,
    INITIALS_UPLOAD,
    SIGNATURE_APPEARANCE_ALLOW_CHANGE,
    SIGNATURE_REASON_OPTION,
    PUBLISH_DOCUMENT_HISTORY,
    PASSWORD_AUTHENTICATION,
    SSL_AUTHENTICATION,
    MOBILE_AUTHENTICATION,
    INTEGRATION,
    BILLING,
    VAT_SUBMISSION,
    TIMEZONE_CHANGE,
    COUNTRY_CHANGE,
    FORM_FIELDS,
    SHAREPOINT,
    REVIEWER,
    INITIALS,
    INPERSONS,
    BULKSIGN,
    ALLOW_AUTO_FINISH,
    ATTACHMENTS,
    SIGNATURE_APPEARANCE_COMPANY_LOGO,
    SIGNATURE_APPEARANCE_DETAILED_SIGNATURE,
    SIGNATURE_APPEARANCE_HAND_SIGNATURE,
    EMAILS_CHANGE,
    MANAGE_PROFILE,
    MANAGE_USERS,
    MANAGE_ROLES,
    MANAGE_GROUPS,
    MANAGE_DOCUMENT,
    MANAGE_TEMPLATES,
    MANAGE_LIBRARY,
    MANAGE_NOTIFICATIONS,
    MANAGE_INTEGRATION,
    MANAGE_ADVANCED,
    MANAGE_REPORT,
    MANAGE_BILLING,
    MANAGE_SIGNING_REASON,
    MANAGE_PERSONAL_DELEGATES,
    MANAGE_PERSONAL_NOTIFICATIONS,
    MANAGE_PERSONAL_SIGNATURE,
    MANAGE_PERSONAL_GROUPS,
    MANAGE_PERSONAL_TEMPLATES,
    MANAGE_PERSONAL_LIBRARY,
    MANAGE_PERSONAL_LEGAL_NOTICES,
    MANAGE_PERSONAL_UPLPAD_AND_SHARE,
    MANAGE_START_FROM_EXISTING_WORKFLOW,
    MANAGE_PERSONAL_SHARE_WITH_ENTERPRISE_CONTACTS_AND_GROUPS,
    MANAGE_PERSONAL_DELEGATE_SIGNING_TO_REGISTERED_USERS,
    ENTERPRISE,
    SELECTED_SIGNING_REASON_OPTION,
    DEFAULT_SIGNING_REASON,
    CLOUD_DRIVE,
    BRANDING,

    //Authentication mechanism for server side signing in Web
    WEB_SERVER_USERPWD_PRIMARY_AUTHENTICATION,

    AUTHENTICATION_SET_OTP,

    //Authentication mechanism for server side signing in Native Apps
    MOBILE_SERVER_USERPWD_PRIMARY_AUTHENTICATION,

    AUTHENTICATION_SET_OTP_MOBILE,

    //List of Appearance
    APPEARANCES,

    EDITOR,
    SEND_A_COPY,
    AUTHORIZE_REMOTE_SIGNING,
    AUTHORIZE_REMOTE_SIGNING_MOBILE,
    PRIMARY_AUTHENTICATION_FOR_LOGIN,
    ALLOW_PUBLIC_AUTHENTICATION_SCHEMES,
    ALLOWED_AUTHENTICATION_MECHANISMS_FOR_LOGIN,
    LOCAL_SIGN_CONNECTIVITY_CHECK_DIALOG_ON_LOGIN,
    ALLOWED_CERTIFICATION_PROFILES,
    ALLOWED_WITNESS_SIGN_PROFILES,
    SELECTED_CERTIFICATION_PROFILES_WEB,
    SELECTED_WITNESS_SIGN_PROFILES_WEB,
    WEB_SERVER_CERTIFICATION_PROFILE_DEFAULT,

    //DEFAULT_WITNESS_SIGN_PROFILE_WEB,
    WITNESS_SIGN_PROFILE_DEFAULT,

    SELECTED_CERTIFICATION_PROFILES_MOBILE,

    //SELECTED_WITNESS_SIGN_PROFILES_MOBILE,
    MOBILE_SERVER_CERTIFICATION_PROFILE_DEFAULT,

    //DEFAULT_WITNESS_SIGN_PROFILE_MOBILE,
    DEFAULT_SIGNATURE_APPEARANCE,

    MANAGE_ENTERPRISE_DOCUMENTS,
    ALLOW_INVISIBLE_SIGNATURE,
    WORKFLOW_MODE,
    WORKFLOW_TYPE,
    ALLOW_USER_TO_DELETE_DOCUMENT,
    ALLOW_OWNER_TO_RECALL_DOCUMENT,
    ALLOW_TO_CHANGE_RECIPIENT,
    MANAGE_ENTERPRISE_LOGS,
    ALLOW_TO_MANAGE_SHARED_SPACES,
    ALLOW_SIGNING,
    CUSTOM_USER_CERTIFICATION_PROFILES_WEB,
    DEFAULT_CUSTOM_USER_CERTIFICATION_PROFILES_WEB,
    SIGNATURE_LEVEL_OF_ASSURANCE,
    ALLOWED_SIGNATURE_LEVEL_OF_ASSURANCE,
    LEVEL_OF_ASSURANCE_DEFAULT,
    ALLOW_MANAGE_SIGNATURE_LOGO,
    LOCATION_DEFAULT,
    FONT_DEFAULT,
    ALLOWED_FONTS,
    ALLOWED_AUTHENTICATION_PROFILES,
    ALLOWED_SIGNING_REASONS,
    ALLOW_ADD_UNIQUE_IDENTIFIER
}

public enum AdminLogAction
{
    LOGGED_OUT, LOGGED_IN, ADMIN_ACTIVITY_ADDED, ADMIN_ACTIVITY_UPDATED, ADMIN_ACTIVITY_DOWNLOADED, ADMIN_ACTIVITY_DELETED, COMMON_RESET,
    ADMIN_ACTIVITY_CHANGE_PASSWORD, ADMIN_ACTIVITY_PUBLISH_CHANGES, ADMIN_ACTIVITY_RESET_SERVICE_PLAN, LOG_ACTIVITY_ACTION_RESET_BRANDING,
    LOG_REQUESTED_PASSWORD_CHANGE, ADMIN_ACTIVITY_MODULE_PASSWORD_UPDATE, ADMIN_TERMS_AND_CONDITIONS_ADDED, ADMIN_TERMS_AND_CONDITIONS_UPDATED, ADMIN_TERMS_AND_CONDITIONS_DELETED,
    ADMIN_ACTIVITY_USER_ACCOUNT_UNLOCKED, COMMON_ACTIVITY_CLONED, COMMON_REVOKE, ADMIN_ACTIVITY_DORMANT, ADMIN_ACTIVITY_ARCHIVED
}

public enum AdminLogModule
{
    ADMIN_ACTIVITY_MODULE_PROFILE, ADMIN_ACTIVITY_MODULE_ACCOUNTS, NULL, ADMIN_ACTIVITY_MODULE_CONFIGURATIONS,
    ADMIN_ACTIVITY_MODULE_SERVICE_PLAN, ADMIN_ACTIVITY_MODULE_ACCESS_CONTROL, ADMIN_ACTIVITY_MODULE_BILLINGS, MAIN_REPORTS,
    ADMIN_ACTIVITY_MODULE_AUTHENTICATE, ADMIN_ACTIVITY_MODULE_LOGS, ADMIN_ACTIVITY_SUB_MODULE_OPERATOR
}

public enum AdminProfiles
{
    AUTHENTICATION = 1,
    SIGNING = 2,
    VERIFICATION = 3,
    CERTIFICATION = 4,
    VIRTUAL = 5
}

public enum AdminRightEnums
{
    Read,
    AddUpdate,
    Delete
}

public enum AuthenticationEnums
{
    ERROR_KEY,
    CAPTCHA_STRING,
    ADMIN_SHOW_CAPTCHA,
    COMMON_ERROR_INCONVENIENCE,
    LOGIN_PASSWORD_INVALID,
    CAPTCHA_INVALID,
    FORGOT_PASSWORD_EMAIL_SUCCESS,
    INVALID_ADMIN,
    COMMON_ERROR_GENERIC,
    ERROR_PUBLISH_CONFIGURATION,
    ERROR_INSTANCE_NOT_RUNNING,
    GOOGLE_CAPTCHA_ENABLE,
    SITE_KEY,
    NEW_PASSWORD_URL
}

public enum LogDetail
{
    COMMON_EMAIL_ADDRESS, IP_ADDRESS, SYSTEM, COMMON_NAME, COMMON_PRIVATE, ADMIN_ACTIVITY_DETAILS_PROVIDERS, CONFIGURATIONS_CONNECTORS_PURPOSE,
    ADMIN_ACTIVITY_DETAILS_DESCRIPTION, ROLE_ALLOW_READ, ROLE_ALLOW_ADD_EDIT, ROLE_ALLOW_DELETE, COMMON_MOBILE_NUMBER,
    COMMON_ACTIVE, ADMIN_ACTIVITY_DETAIL_ACCOUNT_TYPE, SERVICE_PLAN_TYPE_ENTERPRISE, SERVICE_PLAN_TYPE_INDIVIDUAL,
    ADMIN_ACTIVITY_DETAIL_STORAGE, COMMON_UNLIMITED, ADMIN_ACTIVITY_DETAIL_SIGNATURES, ADMIN_ACTIVITY_DETAIL_WORK_FLOWS,
    ADMIN_ACTIVITY_DETAIL_TEMPLATES, ADMIN_ACTIVITY_DETAIL_USERS, ADMIN_ACTIVITY_DETAIL_DOCUMENT_UPLOAD_SIZE, ADMIN_ACTIVITY_DETAIL_PAYMENT_TYPE,
    PAY_REGULARLY, PAY_AS_YOU_GO, ADMIN_ACTIVITY_DETAIL_SERVICE_PLAN_FEATURE, ADMIN_ACTIVITY_OLD_SERVICE_PLAN, USER_ACCESSLEVEL_ENABLED,
    ACCOUNT_CERTIFICATE_ALIAS, AUTHENTICATION_PROFILE_VERIFY_SSL, SIGNATURES_LOCAL, SIGNATURES_MOBILE, SIGNATURES_SERVER,
    ADMIN_ACTIVITY_DETAIL_OLD_OPERATOR_LOG_NAME,
    ADMIN_ACTIVITY_DETAIL_USER_STATUS, ADMIN_ACTIVITY_DETAIL_USER_REGISTERED, ADMIN_ACTIVITY_DETAIL_USER_ACTIVATED, ADMIN_ACTIVITY_DETAIL_USER_UPDATED
}

public enum LogInformationKey
{
    ADMIN_ACTIVITY_INFORMATION_SESSION_DURATION, COMMON_NAME, ADMIN_ACTIVITY_INFORMATION_ACCOUNT_OWNER_EMAIL,
    COMMON_EMAIL_ADDRESS, COMMON_ROLE_NAME, COMMON_GROUP_NAME, CONFIGURATIONS_ACCESS_CONTROL_CERTIFICATE
}

public enum LogSubModule
{
    NULL, ADMIN_ACTIVITY_SUB_MODULE_GENERAL_SETTINGS, ADMIN_ACTIVITY_SUB_MODULE_CONNECTORS,
    ADMIN_ACTIVITY_SUB_MODULE_AUTHENTICATION_PROFILES, ADMIN_ACTIVITY_SUB_MODULE_CERTIFICATIONS,
    ADMIN_ACTIVITY_SUB_MODULE_SIGNING_PROFILES, ADMIN_ACTIVITY_SUB_MODULE_VERIFICATIONS_PROFILES,
    ADMIN_ACTIVITY_SUB_MODULE_EVIDENCE_REPORT, ADMIN_ACTIVITY_SUB_MODULE_BILLING, ADMIN_ACTIVITY_SUB_MODULE_BRANDING,
    ADMIN_ACTIVITY_SUB_MODULE_LICENSE, ADMIN_ACTIVITY_SUB_MODULE_ROLE, ADMIN_ACTIVITY_SUB_MODULE_SEARCH,
    ADMIN_ACTIVITY_SUB_MODULE_MANUAL_PAYMENT, ADMIN_ACTIVITY_SUB_MODULE_SERVICE_PLANS,
    ADMIN_ACTIVITY_SUB_MODULE_PROFILE, ADMIN_ACTIVITY_SUB_MODULE_ADMINISTRATOR, ADMIN_ACTIVITY_SUB_MODULE_DATA_DIRECTORY,
    ADMIN_ACTIVITY_SUB_MODULE_INSTANCES,
    ADMIN_ACTIVITY_SUB_MODULE_OPERATOR, ADMIN_ACTIVITY_SUB_MODULE_DATA_SECURITY,
    ADMIN_ACTIVITY_SUB_MODULE_DOMAINS,
    ADMIN_ACTIVITY_SUB_MODULE_TERMS_AND_CONDITIONS, ADMIN_ACTIVITY_SUB_MODULE_REDIS, ADMIN_ACTIVITY_SUB_MODULE_VIRTUAL_PROFILES,

    REPORTS_DOCUMENT_STATISTICS,
    REPORTS_SIGNATURE_STATISTICS,
    REPORTS_SMS_COMSUMED_STATISTICS,
    REPORTS_ACCOUNT_SEARCH_REGISTRATIONS,
    REPORTS_ACCOUNT_SEARCH_LOGIN,
    REPORTS_ACCOUNT_SEARCH_WORKFLOWS,
    REPORTS_ACCOUNT_SEARCH_SIGNATURES,
    REPORTS_BILLING_TITLE,
    REPORTS_SERVICEPLAN_TITLE,
    ACCOUNTS_USER_CERTIFICATE_INFORMATION
}

public enum SearchSection
{
    ACCOUNT = 0,
    BILLING = 1,
    LOG = 2,
    ACCOUNT_REPORT = 4
}
